/**
 * `/ext/flags`' two `presentation` surfaces, against the real shell.
 *
 * Flags is the extension where the hard rule bites, so this file is as much
 * about what does *not* happen as about what the presets paint.
 *
 * 1. **Two surfaces, because a control's presentation is configured next to
 *    that control.** `FlagsOptions.presentation` is the chip;
 *    `PromotedFlag.presentation` is one promoted flag, invoked per flag. The
 *    alternative — one flags-level callback receiving `FlagsSnapshot |
 *    FlagView` — would make every consumer narrow a union to find out which
 *    control it was handed.
 * 2. **A `ReactNode` never enters the store.** This store republishes on a
 *    *string* signature, so an unsignable node either never publishes or
 *    republishes every 250 ms tick — and it would sit inside the object
 *    `diagnostics()` serialises, one refactor away from a circular-structure
 *    throw inside a click handler. `PromotedFlag.icon` therefore stays
 *    `string`, rich icons live on `PromotedFlag.presentation`, and the
 *    resolved presentations reach `ui.tsx` as props from the factory closure.
 *    "the store never sees a node" below is the evidence.
 * 3. **The hand-written chip stays hand-written.** This chip has no dot and
 *    the kit `Chip` always renders one, so it is not routed through `Chip`;
 *    what it gained is kit's `renderCompactParts` slotting into the span it
 *    already had. The default literals below are the proof that slotted in
 *    byte-for-byte.
 *
 * Every literal here was generated by capture from a mounted toolbar, then
 * diffed against the same capture taken before this change. Regenerate them
 * only against a deliberate, documented change to flags' bar DOM: every
 * consumer's CSS and every Playwright selector reads these attributes.
 *
 * [dev-toolbar/plans/bar-presentation-icons-v1 §5]
 */
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { isValidElement } from "react";
import { act } from "@testing-library/react";
import { cleanupToolbar, mountToolbar } from "@nejcm/dev-toolbar/testing";
import type { CompactPreset, CompactRenderContext } from "@nejcm/dev-toolbar/kit";
import { flags } from "../index";
import type { FlagsOptions } from "../index";
import { createFlagsRuntime } from "../runtime";
import type { FlagView, FlagsSnapshot, PromotedFlag } from "../types";

/** Two flags, both promoted: a boolean switch and a string that paints a value. */
const CATALOGUE = [
  { key: "new-header", type: "boolean" as const, defaultValue: true },
  { key: "checkout.tier", type: "string" as const, defaultValue: "gold" },
];

const BASE: FlagsOptions = {
  flags: CATALOGUE,
  promoted: [{ flagKey: "new-header" }, { flagKey: "checkout.tier" }],
};

/**
 * Tears down whatever is already mounted first: several tests here compare two
 * presentations of the same extension, and the testing helpers query the
 * document rather than one root.
 */
const mount = (options: FlagsOptions = {}) => {
  cleanupToolbar();
  return mountToolbar(null, {
    extensions: [flags({ ...BASE, ...options })],
    layout: { barWidth: 900, itemWidth: 200 },
  });
};

/** Everything `/ext/flags` puts in the bar: both promoted controls and the chip. */
const barItem = (options: FlagsOptions = {}): HTMLElement =>
  mount(options).toolbar.item("flags") as HTMLElement;

/** The `⋮` entry, with the bar collapsed to nothing. */
const overflow = (options: FlagsOptions = {}): HTMLElement => {
  const { toolbar } = mount(options);
  toolbar.resize(60);
  expect(toolbar.isOverflowed("flags")).toBe(true);
  toolbar.openOverflow();
  const wrapper = toolbar
    .overflowMenu()
    ?.querySelector<HTMLElement>('[data-dtb-part="flag-overflow"]');
  expect(wrapper).not.toBeNull();
  return wrapper as HTMLElement;
};

const chipOf = (root: HTMLElement): HTMLElement =>
  root.querySelector('[data-dtb-part="flag-chip"]') as HTMLElement;

const triggerOf = (root: HTMLElement): HTMLElement =>
  root.querySelector(
    '[data-dtb-part="trigger"], [data-dtb-part="flag-overflow-trigger"]',
  ) as HTMLElement;

const promotedOf = (root: HTMLElement, key: string): HTMLElement =>
  root.querySelector(`[data-dtb-part="flag-promoted"][data-dtb-flag="${key}"]`) as HTMLElement;

const textIn = (element: Element, selector: string): string | null =>
  element.querySelector(selector)?.textContent ?? null;

const countIn = (element: Element, selector: string): number =>
  element.querySelectorAll(selector).length;

/**
 * The promoted control's text span, located structurally.
 *
 * It is deliberately unnamed — that is what it has always been, and naming it
 * would move the default bytes below. The dot and the back-compat glyph are
 * both `aria-hidden`, and the value span carries a part, so "the one direct
 * child span with neither" is exactly the label.
 */
const promotedText = (button: Element): string | null => {
  const span = [...button.querySelectorAll(":scope > span")].find(
    (node) => !node.hasAttribute("data-dtb-part") && !node.hasAttribute("aria-hidden"),
  );
  return span?.textContent ?? null;
};

/** A consumer's own inline `<svg>` — the proof that nothing was bundled. */
const ICON = (
  <svg viewBox="0 0 16 16" data-icon="flag">
    <path d="M2 2h12v6H2z" />
  </svg>
);

/** `presentation` on one promoted flag, leaving the other alone. */
const promotedWith = (
  key: string,
  presentation: PromotedFlag["presentation"],
  extra: Omit<PromotedFlag, "flagKey" | "presentation"> = {},
): FlagsOptions => ({
  promoted:
    BASE.promoted === undefined
      ? []
      : [
          ...(BASE.promoted as readonly PromotedFlag[]).filter((entry) => entry.flagKey !== key),
          { flagKey: key, ...extra, ...(presentation === undefined ? {} : { presentation }) },
        ].sort((a, b) => (a.flagKey === "new-header" ? -1 : b.flagKey === "new-header" ? 1 : 0)),
});

afterEach(cleanupToolbar);

describe("the default presentation", () => {
  // Captured from a mounted toolbar and diffed against the same capture taken
  // before `presentation` existed. Both promoted controls and the chip, in one
  // string, because the promoted siblings are part of what this item paints.
  const DEFAULT_BAR =
    '<button type="button" data-dtb-part="flag-promoted" data-dtb-flag="new-header" data-dtb-overridden="false" aria-label="new-header" title="new-header = true · from default · click to open the flags panel">' +
    '<span data-dtb-part="flag-promoted-dot" data-dtb-kind="dot" aria-hidden="true"></span>' +
    "<span>new-header</span></button>" +
    '<button type="button" data-dtb-part="flag-promoted" data-dtb-flag="checkout.tier" data-dtb-overridden="false" aria-label="checkout.tier, gold" title="checkout.tier = gold · from default · click to open the flags panel">' +
    '<span data-dtb-part="flag-promoted-dot" data-dtb-kind="dot" aria-hidden="true"></span>' +
    "<span>checkout.tier</span>" +
    '<span data-dtb-part="flag-promoted-value" data-dtb-kind="value">gold</span></button>' +
    '<button type="button" data-dtb-part="trigger" aria-expanded="false" aria-label="Flags" title="Feature flags: 2 · 0 locally overridden · read-only">' +
    '<span data-dtb-part="flag-chip" data-dtb-kind="chip" data-dtb-overridden="false">' +
    '<span data-dtb-part="flag-label" data-dtb-kind="label">flags</span>' +
    '<span data-dtb-part="flag-count">2</span></span></button>';

  // The `⋮` entry. Note the chip still says "flags", not "Flags": unlike the
  // Group A chips, this one has never swung to its `label` when overflowed, so
  // its `CompactDefaults.overflow` is `"short"` and the default stays
  // byte-identical here too. A *preset* still forces the full word.
  const DEFAULT_OVERFLOW =
    '<div data-dtb-part="flag-overflow">' +
    '<button type="button" data-dtb-part="flag-promoted" data-dtb-flag="new-header" data-dtb-overridden="false" aria-label="new-header" title="new-header = true · from default · click to open the flags panel">' +
    '<span data-dtb-part="flag-promoted-dot" data-dtb-kind="dot" aria-hidden="true"></span>' +
    "<span>new-header</span></button>" +
    '<button type="button" data-dtb-part="flag-promoted" data-dtb-flag="checkout.tier" data-dtb-overridden="false" aria-label="checkout.tier, gold" title="checkout.tier = gold · from default · click to open the flags panel">' +
    '<span data-dtb-part="flag-promoted-dot" data-dtb-kind="dot" aria-hidden="true"></span>' +
    "<span>checkout.tier</span>" +
    '<span data-dtb-part="flag-promoted-value" data-dtb-kind="value">gold</span></button>' +
    '<button type="button" data-dtb-part="flag-overflow-trigger" aria-expanded="false" aria-label="Flags" title="Feature flags: 2 · 0 locally overridden · read-only">' +
    '<span data-dtb-part="flag-chip" data-dtb-kind="chip" data-dtb-overridden="false">' +
    '<span data-dtb-part="flag-label" data-dtb-kind="label">flags</span>' +
    '<span data-dtb-part="flag-count">2</span></span></button></div>';

  // A non-default state, so nothing above passes by virtue of every value
  // being at rest: one flag locally overridden (the chip's count, both
  // `data-dtb-overridden`s and the promoted title change), a writable adapter
  // so the boolean is a `role="switch"`, a back-compat string `icon`, and a
  // promoted `label`.
  const EDITED_BAR =
    '<button type="button" data-dtb-part="flag-promoted" data-dtb-flag="new-header" data-dtb-overridden="false" aria-label="new-header" role="switch" aria-checked="true" title="new-header = true · from default · click to toggle">' +
    '<span data-dtb-part="flag-promoted-dot" data-dtb-kind="dot" aria-hidden="true"></span>' +
    '<span aria-hidden="true">A</span><span>new-header</span></button>' +
    '<button type="button" data-dtb-part="flag-promoted" data-dtb-flag="checkout.tier" data-dtb-overridden="true" aria-label="Tier, silver" title="checkout.tier = silver · locally overridden — the app\'s own value is gold · click to open the flags panel">' +
    '<span data-dtb-part="flag-promoted-dot" data-dtb-kind="dot" aria-hidden="true"></span>' +
    "<span>Tier</span>" +
    '<span data-dtb-part="flag-promoted-value" data-dtb-kind="value">silver</span></button>' +
    '<button type="button" data-dtb-part="trigger" aria-expanded="false" aria-label="Flags" title="Feature flags: 2 · 1 locally overridden">' +
    '<span data-dtb-part="flag-chip" data-dtb-kind="chip" data-dtb-overridden="true">' +
    '<span data-dtb-part="flag-label" data-dtb-kind="label">flags</span>' +
    '<span data-dtb-part="flag-count">1 overridden</span></span></button>';

  it("paints the bar byte-identically with no option at all", () => {
    expect(barItem().innerHTML).toBe(DEFAULT_BAR);
  });

  it("paints the ⋮ entry byte-identically with no option at all", () => {
    expect(overflow().outerHTML).toBe(DEFAULT_OVERFLOW);
  });

  it("paints an edited, overridden bar byte-identically", async () => {
    const { toolbar } = mount({
      onOverride: () => {},
      promoted: [
        { flagKey: "new-header", icon: "A" },
        { flagKey: "checkout.tier", label: "Tier" },
      ],
    });
    await act(async () => {
      await toolbar.invokeCommand("flags.set", { key: "checkout.tier", value: "silver" });
    });
    expect((toolbar.item("flags") as HTMLElement).innerHTML).toBe(EDITED_BAR);
  });

  it('is unmoved by icon: "" — an empty string is not an icon', () => {
    // `PromotedFlag.icon` has always been painted on truthiness
    // (`view.promotedIcon ? <span …> : null`), so `""` paints *nothing*: no
    // span, and therefore no `gap` between the dot and the label. Routing the
    // glyph through the icon slot must not turn `""` into a slot filler —
    // pinned on both surfaces because it is a one-character regression.
    const empty = { promoted: [{ flagKey: "new-header", icon: "" }, { flagKey: "checkout.tier" }] };
    expect(barItem(empty).innerHTML).toBe(DEFAULT_BAR);
    expect(overflow(empty).outerHTML).toBe(DEFAULT_OVERFLOW);
  });

  it('is what an explicit "default" resolves to', () => {
    expect(barItem({ presentation: "default" }).innerHTML).toBe(DEFAULT_BAR);
    expect(overflow({ presentation: "default" }).outerHTML).toBe(DEFAULT_OVERFLOW);
  });

  it("is unchanged by an icon the chip's default paints no slot for", () => {
    // The chip has never painted an icon, so its `CompactDefaults` name no
    // icon slot and a bare icon does nothing: the four knobs are meaningless
    // apart, which is why they are one option.
    expect(barItem({ presentation: { preset: "default", icon: ICON } }).innerHTML).toBe(
      DEFAULT_BAR,
    );
  });

  it("lets a promoted flag's default tree take a rich icon, because it has a slot", () => {
    /**
     * The one place `"default"` plus a bare `icon` is *not* a no-op, and
     * deliberately so: a promoted control has painted an icon since it
     * existed — `PromotedFlag.icon`, the string glyph — so its
     * `CompactDefaults` name that slot, and `presentation.icon` fills it. That
     * is the upgrade path off the string field, which stays `string` because
     * widening it would put a React element in the store. Group A has no such
     * slot, hence the difference.
     */
    const button = promotedOf(
      barItem(promotedWith("checkout.tier", { preset: "default", icon: ICON })),
      "checkout.tier",
    );
    expect(countIn(button, '[data-dtb-part="flag-promoted-icon"] svg')).toBe(1);
    // Everything else about the default tree is untouched.
    expect(promotedText(button)).toBe("checkout.tier");
    expect(textIn(button, '[data-dtb-part="flag-promoted-value"]')).toBe("gold");
    expect(button.getAttribute("aria-label")).toBe("checkout.tier, gold");
  });
});

interface Painted {
  icon: number;
  text: string | null;
  value: string | null;
}

interface PresetRow {
  preset: CompactPreset;
  /** The chip, in the bar / in the `⋮` menu / in the bar with no icon supplied. */
  chipBar: Painted;
  chipMenu: Painted;
  chipBare: Painted;
  /** The `checkout.tier` promoted control, same three places. */
  flagBar: Painted;
  flagMenu: Painted;
  flagBare: Painted;
  /**
   * The `new-header` promoted **boolean**, in the bar, with and without an icon.
   *
   * Its own columns because a boolean is the one control with no value slot —
   * a switch announces its own state — so `"value"` and an iconless
   * `"icon-value"` would resolve to nothing at all. That is the blank-control
   * hole kit's guarantee 1 does not cover (it is about `"icon"` alone), and
   * these two columns are where the text fallback that closes it is pinned.
   */
  boolBar: Painted;
  boolBare: Painted;
}

/**
 * Every member of the preset union, on both surfaces. The completeness check
 * below fails if a member goes missing.
 *
 * The promoted control has **one** text — its promoted label *is* its identity
 * — so `short` and `full` are the same word and the `⋮` rule is a no-op for
 * it. The chip has two, and the menu forces the full one under every preset.
 */
const PRESETS: readonly PresetRow[] = [
  {
    preset: "default",
    chipBar: { icon: 0, text: "flags", value: "2" },
    chipMenu: { icon: 0, text: "flags", value: "2" },
    chipBare: { icon: 0, text: "flags", value: "2" },
    flagBar: { icon: 1, text: "checkout.tier", value: "gold" },
    flagMenu: { icon: 1, text: "checkout.tier", value: "gold" },
    // No icon supplied, and the default tree paints one only when there is
    // one: `CompactDefaults` is handed back verbatim, so the presence check is
    // the extension's.
    flagBare: { icon: 0, text: "checkout.tier", value: "gold" },
    boolBar: { icon: 1, text: "new-header", value: null },
    boolBare: { icon: 0, text: "new-header", value: null },
  },
  {
    preset: "icon",
    chipBar: { icon: 1, text: null, value: null },
    // Guarantee 2 forces text in the menu — and only text, so the row loses
    // the count today's default paints. Intended, and pinned so it reads as a
    // decision rather than surfacing later as a regression.
    chipMenu: { icon: 1, text: "Flags", value: null },
    // Guarantee 1: an icon-only preset with no icon paints text, never nothing.
    chipBare: { icon: 0, text: "flags", value: null },
    flagBar: { icon: 1, text: null, value: null },
    flagMenu: { icon: 1, text: "checkout.tier", value: null },
    flagBare: { icon: 0, text: "checkout.tier", value: null },
    boolBar: { icon: 1, text: null, value: null },
    boolBare: { icon: 0, text: "new-header", value: null },
  },
  {
    preset: "icon-value",
    chipBar: { icon: 1, text: null, value: "2" },
    chipMenu: { icon: 1, text: "Flags", value: "2" },
    chipBare: { icon: 0, text: null, value: "2" },
    flagBar: { icon: 1, text: null, value: "gold" },
    flagMenu: { icon: 1, text: "checkout.tier", value: "gold" },
    flagBare: { icon: 0, text: null, value: "gold" },
    // A boolean paints no value, so with an icon this is icon-only — and with
    // none it would be the bare dot, which the text fallback closes.
    boolBar: { icon: 1, text: null, value: null },
    boolBare: { icon: 0, text: "new-header", value: null },
  },
  {
    // The short bar word, the full label in the menu: the "which text" rule,
    // asserted rather than described.
    preset: "icon-label",
    chipBar: { icon: 1, text: "flags", value: null },
    chipMenu: { icon: 1, text: "Flags", value: null },
    chipBare: { icon: 0, text: "flags", value: null },
    flagBar: { icon: 1, text: "checkout.tier", value: null },
    flagMenu: { icon: 1, text: "checkout.tier", value: null },
    flagBare: { icon: 0, text: "checkout.tier", value: null },
    boolBar: { icon: 1, text: "new-header", value: null },
    boolBare: { icon: 0, text: "new-header", value: null },
  },
  {
    preset: "label",
    // "label" names no icon, so a supplied one is not painted.
    chipBar: { icon: 0, text: "flags", value: null },
    chipMenu: { icon: 0, text: "Flags", value: null },
    chipBare: { icon: 0, text: "flags", value: null },
    flagBar: { icon: 0, text: "checkout.tier", value: null },
    flagMenu: { icon: 0, text: "checkout.tier", value: null },
    flagBare: { icon: 0, text: "checkout.tier", value: null },
    boolBar: { icon: 0, text: "new-header", value: null },
    boolBare: { icon: 0, text: "new-header", value: null },
  },
  {
    preset: "value",
    chipBar: { icon: 0, text: null, value: "2" },
    chipMenu: { icon: 0, text: "Flags", value: "2" },
    chipBare: { icon: 0, text: null, value: "2" },
    flagBar: { icon: 0, text: null, value: "gold" },
    flagMenu: { icon: 0, text: "checkout.tier", value: "gold" },
    flagBare: { icon: 0, text: null, value: "gold" },
    // `"value"` on a boolean names the one part it cannot paint. Rather than a
    // switch that is a bare dot, it falls back to text: a blank control is
    // worse than an unstyled one.
    boolBar: { icon: 0, text: "new-header", value: null },
    boolBare: { icon: 0, text: "new-header", value: null },
  },
];

const paintedChip = (root: HTMLElement): Painted => {
  const chip = chipOf(root);
  return {
    icon: countIn(chip, '[data-dtb-part="flag-icon"]'),
    text: textIn(chip, '[data-dtb-part="flag-label"]'),
    value: textIn(chip, '[data-dtb-part="flag-count"]'),
  };
};

const paintedFlag = (root: HTMLElement, key = "checkout.tier"): Painted => {
  const button = promotedOf(root, key);
  return {
    icon: countIn(button, '[data-dtb-part="flag-promoted-icon"]'),
    text: promotedText(button),
    value: textIn(button, '[data-dtb-part="flag-promoted-value"]'),
  };
};

describe("presets", () => {
  it("covers every member of the preset union", () => {
    const members: Record<CompactPreset, true> = {
      default: true,
      icon: true,
      "icon-value": true,
      "icon-label": true,
      label: true,
      value: true,
    };
    expect(PRESETS.map((row) => row.preset).sort()).toEqual(Object.keys(members).sort());
  });

  it.each(PRESETS)("$preset paints the chip in the bar", ({ preset, chipBar }) => {
    expect(paintedChip(barItem({ presentation: { preset, icon: ICON } }))).toEqual(chipBar);
  });

  it.each(PRESETS)("$preset paints the chip in the ⋮ menu", ({ preset, chipMenu }) => {
    expect(paintedChip(overflow({ presentation: { preset, icon: ICON } }))).toEqual(chipMenu);
  });

  it.each(PRESETS)("$preset paints the chip with no icon supplied", ({ preset, chipBare }) => {
    // The bare-preset shorthand, which is the 90% call: `presentation: "icon"`.
    expect(paintedChip(barItem({ presentation: preset }))).toEqual(chipBare);
  });

  it.each(PRESETS)("$preset paints a promoted flag in the bar", ({ preset, flagBar }) => {
    expect(paintedFlag(barItem(promotedWith("checkout.tier", { preset, icon: ICON })))).toEqual(
      flagBar,
    );
  });

  it.each(PRESETS)("$preset paints a promoted flag in the ⋮ menu", ({ preset, flagMenu }) => {
    expect(paintedFlag(overflow(promotedWith("checkout.tier", { preset, icon: ICON })))).toEqual(
      flagMenu,
    );
  });

  it.each(PRESETS)("$preset paints a promoted flag with no icon", ({ preset, flagBare }) => {
    expect(paintedFlag(barItem(promotedWith("checkout.tier", preset)))).toEqual(flagBare);
  });

  it.each(PRESETS)("$preset paints a promoted boolean in the bar", ({ preset, boolBar }) => {
    expect(
      paintedFlag(barItem(promotedWith("new-header", { preset, icon: ICON })), "new-header"),
    ).toEqual(boolBar);
  });

  it.each(PRESETS)("$preset never leaves a promoted boolean blank", ({ preset, boolBare }) => {
    // A boolean has no value slot, so `"value"` and an iconless `"icon-value"`
    // would resolve to a control that is nothing but its dot. Kit's guarantee 1
    // covers `"icon"` alone; this is the same principle applied where the
    // "other part" a preset relies on does not exist.
    const button = promotedOf(barItem(promotedWith("new-header", preset)), "new-header");
    expect(paintedFlag(barItem(promotedWith("new-header", preset)), "new-header")).toEqual(
      boolBare,
    );
    expect(button.textContent).not.toBe("");
  });

  it.each(PRESETS)("$preset is one control's business, not the extension's", ({ preset }) => {
    // `PromotedFlag.presentation` is per flag: the sibling that configured
    // nothing keeps painting its default, which a flags-level callback taking
    // `FlagsSnapshot | FlagView` could not express without a union to narrow.
    const item = barItem(promotedWith("checkout.tier", { preset, icon: ICON }));
    expect(promotedText(promotedOf(item, "new-header"))).toBe("new-header");
    expect(countIn(promotedOf(item, "new-header"), '[data-dtb-part="flag-promoted-icon"]')).toBe(0);
    // And the chip is untouched by a promoted flag's preset.
    expect(paintedChip(item)).toEqual({ icon: 0, text: "flags", value: "2" });
  });

  it.each(PRESETS)("$preset changes text, never state", ({ preset }) => {
    const item = barItem({
      onOverride: () => {},
      presentation: { preset, icon: ICON },
      ...promotedWith("new-header", { preset, icon: ICON }),
    });
    const trigger = triggerOf(item);
    expect(trigger.getAttribute("aria-expanded")).toBe("false");
    expect(trigger.getAttribute("aria-label")).toBe("Flags");
    expect(trigger.getAttribute("title")).toBe("Feature flags: 2 · 0 locally overridden");
    expect(chipOf(item).getAttribute("data-dtb-overridden")).toBe("false");

    const promoted = promotedOf(item, "new-header");
    // A promoted boolean stays a switch that announces its own state, and
    // keeps the dot the preset never sees.
    expect(promoted.getAttribute("role")).toBe("switch");
    expect(promoted.getAttribute("aria-checked")).toBe("true");
    expect(promoted.getAttribute("data-dtb-flag")).toBe("new-header");
    expect(promoted.getAttribute("data-dtb-overridden")).toBe("false");
    expect(promoted.getAttribute("aria-label")).toBe("new-header");
    expect(promoted.querySelector('[data-dtb-part="flag-promoted-dot"]')).not.toBeNull();
  });

  it.each(PRESETS)("$preset changes text, never state, in the ⋮ menu too", ({ preset }) => {
    // The same claim on the other surface. State attributes are written on the
    // button and the chip span, both of which a preset — and a `render`
    // callback — supply only the *children* of, so overflowing cannot move them.
    const menu = overflow({
      onOverride: () => {},
      presentation: { preset, icon: ICON },
      ...promotedWith("new-header", { preset, icon: ICON }),
    });
    const trigger = triggerOf(menu);
    expect(trigger.getAttribute("aria-expanded")).toBe("false");
    expect(trigger.getAttribute("aria-label")).toBe("Flags");
    expect(trigger.getAttribute("title")).toBe("Feature flags: 2 · 0 locally overridden");
    expect(chipOf(menu).getAttribute("data-dtb-overridden")).toBe("false");

    const promoted = promotedOf(menu, "new-header");
    expect(promoted.getAttribute("role")).toBe("switch");
    expect(promoted.getAttribute("aria-checked")).toBe("true");
    expect(promoted.getAttribute("data-dtb-flag")).toBe("new-header");
    expect(promoted.getAttribute("data-dtb-overridden")).toBe("false");
    expect(promoted.getAttribute("aria-label")).toBe("new-header");
    expect(promoted.querySelector('[data-dtb-part="flag-promoted-dot"]')).not.toBeNull();
  });

  it("hides the icon from assistive technology and clamps it, on both surfaces", () => {
    const item = barItem({
      presentation: { preset: "icon", icon: ICON },
      ...promotedWith("checkout.tier", { preset: "icon", icon: ICON }),
    });
    for (const part of ["flag-icon", "flag-promoted-icon"]) {
      const glyph = item.querySelector(`[data-dtb-part="${part}"]`);
      expect(glyph?.getAttribute("aria-hidden")).toBe("true");
      expect(glyph?.getAttribute("data-dtb-kind")).toBe("glyph");
      expect(glyph?.querySelector("svg")).not.toBeNull();
    }
  });
});

describe("the back-compat string icon", () => {
  /**
   * `PromotedFlag.icon` stays `string` on purpose — widening it to `ReactNode`
   * is what would put an element in the snapshot. It keeps the bare
   * `aria-hidden` span it has always rendered rather than moving into `Glyph`,
   * because moving it would change the default bytes; what it gained is a
   * place in the icon slot, so it survives a preset instead of vanishing.
   */
  it("fills the icon slot when no presentation icon was supplied", () => {
    const item = barItem(promotedWith("checkout.tier", "icon", { icon: "A" }));
    const button = promotedOf(item, "checkout.tier");
    // Guarantee 1 does *not* fire: there is an icon, it is just a string one.
    expect(promotedText(button)).toBeNull();
    expect(countIn(button, '[data-dtb-part="flag-promoted-icon"]')).toBe(0);
    expect(
      button.querySelector(":scope > span[aria-hidden]:not([data-dtb-part])")?.textContent,
    ).toBe("A");
  });

  it("yields to a presentation icon rather than painting both", () => {
    const item = barItem(
      promotedWith("checkout.tier", { preset: "icon", icon: ICON }, { icon: "A" }),
    );
    const button = promotedOf(item, "checkout.tier");
    expect(countIn(button, '[data-dtb-part="flag-promoted-icon"]')).toBe(1);
    expect(button.textContent).toBe("");
  });

  it.each([
    ["false, from a && guard", false],
    ["true", true],
    ["an empty string", ""],
  ])("fills the slot when a rich icon declines with %s", (_name, value) => {
    // One rule, both suppliers. "Declines" is `hasPaintableIcon`, so a rich
    // `icon: (v) => v.overridden && <I />` returning `false` falls back to the
    // legacy glyph exactly as `undefined` does — rather than blocking the
    // fallback *and* counting as an icon, which would have painted an empty
    // span and suppressed guarantee 1 under `preset: "icon"`.
    const button = promotedOf(
      barItem(
        promotedWith(
          "checkout.tier",
          { preset: "icon", icon: () => value as never },
          { icon: "A" },
        ),
      ),
      "checkout.tier",
    );
    expect(promotedText(button)).toBeNull();
    expect(countIn(button, '[data-dtb-part="flag-promoted-icon"]')).toBe(0);
    expect(
      button.querySelector(":scope > span[aria-hidden]:not([data-dtb-part])")?.textContent,
    ).toBe("A");
  });

  it('does not fill the icon slot with "", which would leave the control blank', () => {
    // The other half of the same rule. `""` is not an icon, so `hasIcon` is
    // false and kit's guarantee 1 fires: an icon-only preset with no icon
    // paints text. Treated as present instead, `"icon"` would resolve to
    // icon-only, paint an empty `aria-hidden` span for it, and leave a switch
    // that is a bare dot with `textContent === ""` — the exact hole guarantee 1
    // exists to close.
    const button = promotedOf(
      barItem(promotedWith("checkout.tier", "icon", { icon: "" })),
      "checkout.tier",
    );
    expect(button.querySelector(":scope > span[aria-hidden]:not([data-dtb-part])")).toBeNull();
    expect(countIn(button, '[data-dtb-part="flag-promoted-icon"]')).toBe(0);
    expect(promotedText(button)).toBe("checkout.tier");
    expect(button.textContent).not.toBe("");
  });

  it("is dropped by a preset that names no icon", () => {
    const button = promotedOf(
      barItem(promotedWith("checkout.tier", "label", { icon: "A" })),
      "checkout.tier",
    );
    expect(button.querySelector(":scope > span[aria-hidden]:not([data-dtb-part])")).toBeNull();
    expect(promotedText(button)).toBe("checkout.tier");
  });
});

describe("a function icon", () => {
  it("is invoked with the snapshot on the chip and the view on a promoted flag", () => {
    const snapshots: FlagsSnapshot[] = [];
    const views: FlagView[] = [];
    const item = barItem({
      presentation: {
        preset: "icon",
        icon: (snapshot: FlagsSnapshot) => {
          snapshots.push(snapshot);
          return <svg data-icon={`chip-${snapshot.flags.length}`} />;
        },
      },
      ...promotedWith("checkout.tier", {
        preset: "icon",
        icon: (view: FlagView) => {
          views.push(view);
          return <svg data-icon={view.key} />;
        },
      }),
    });
    expect(snapshots[0]?.flags.length).toBe(2);
    expect(views[0]?.key).toBe("checkout.tier");
    expect(item.querySelector('[data-dtb-part="flag-icon"] svg')?.getAttribute("data-icon")).toBe(
      "chip-2",
    );
    expect(
      item.querySelector('[data-dtb-part="flag-promoted-icon"] svg')?.getAttribute("data-icon"),
    ).toBe("checkout.tier");
  });

  it("paints text when it returns nothing", () => {
    // Guarantee 1 applies per control, after the function has been resolved.
    const item = barItem({
      presentation: { preset: "icon", icon: () => undefined },
      ...promotedWith("checkout.tier", { preset: "icon", icon: () => undefined }),
    });
    expect(paintedChip(item)).toEqual({ icon: 0, text: "flags", value: null });
    expect(paintedFlag(item)).toEqual({ icon: 0, text: "checkout.tier", value: null });
  });
});

describe("which promotion is in force", () => {
  /**
   * A `presentation` belongs to one **entry** of `promoted`, not to a flag key.
   *
   * Two entries may name the same key with different `startAt`/`expiresAt`/
   * `audience` windows, and only the runtime knows which is eligible right now.
   * It publishes that as `FlagView.promotedIndex` — a number, so it is signable
   * and the hard rule is untouched — and the UI reads its map with that index.
   * Keyed by `flagKey` instead, an expired or wrong-audience entry's icon would
   * paint on the live entry's label.
   */
  const LIVE = { preset: "icon", icon: ICON } as const;

  /**
   * The same config, read headless.
   *
   * `snapshot.promoted` is the list the bar maps over, and "which entry won" is
   * only half the claim: the loser must not *also* be in it. Two entries naming
   * one key used to push that key's single view once per entry, so the bar
   * painted two identical switches and React logged two "same key" errors.
   * Hence both the length here and the DOM count below — and the `console.error`
   * guard on this whole `describe`, which is what would catch it coming back
   * through a path neither count covers.
   */
  const promotedIn = (options: FlagsOptions): readonly FlagView[] => {
    const runtime = createFlagsRuntime({ flags: CATALOGUE, ...options });
    const promoted = runtime.store.peek().promoted;
    runtime.store.destroy();
    return promoted;
  };

  const countPromoted = (item: HTMLElement, key: string): number =>
    countIn(item, `[data-dtb-part="flag-promoted"][data-dtb-flag="${key}"]`);

  let consoleError: ReturnType<typeof vi.spyOn>;

  beforeEach(() => {
    consoleError = vi.spyOn(console, "error").mockImplementation(() => {});
  });

  afterEach(() => {
    // A duplicate in `snapshot.promoted` is a React key collision, and React
    // reports that on `console.error` rather than by throwing.
    expect(consoleError).not.toHaveBeenCalled();
    consoleError.mockRestore();
  });

  it("uses the eligible entry's presentation when an earlier one has expired", () => {
    const options: FlagsOptions = {
      promoted: [
        {
          flagKey: "checkout.tier",
          label: "Expired",
          expiresAt: "2000-01-01T00:00:00.000Z",
          presentation: "label",
        },
        { flagKey: "checkout.tier", label: "Live", presentation: LIVE },
      ],
    };
    const item = barItem(options);
    const button = promotedOf(item, "checkout.tier");
    expect(countIn(button, '[data-dtb-part="flag-promoted-icon"]')).toBe(1);
    // The label comes from the same entry, so the two cannot disagree.
    expect(promotedText(button)).toBeNull();
    expect(button.getAttribute("aria-label")).toBe("Live, gold");
    // The expired entry contributes nothing — not even a second copy of the
    // view it names.
    expect(promotedIn(options)).toHaveLength(1);
    expect(countPromoted(item, "checkout.tier")).toBe(1);
  });

  it("uses the eligible entry's presentation when an earlier one is for another audience", () => {
    const options: FlagsOptions = {
      audience: ["dev"],
      promoted: [
        { flagKey: "checkout.tier", audience: ["qa"], label: "QA", presentation: LIVE },
        { flagKey: "checkout.tier", label: "Everyone", presentation: "label" },
      ],
    };
    const item = barItem(options);
    const button = promotedOf(item, "checkout.tier");
    expect(countIn(button, '[data-dtb-part="flag-promoted-icon"]')).toBe(0);
    expect(promotedText(button)).toBe("Everyone");
    expect(promotedIn(options)).toHaveLength(1);
    expect(countPromoted(item, "checkout.tier")).toBe(1);
  });

  it("takes the first eligible entry when two name the same key", () => {
    const options: FlagsOptions = {
      promoted: [
        { flagKey: "checkout.tier", label: "First", presentation: LIVE },
        { flagKey: "checkout.tier", label: "Second", presentation: "label" },
      ],
    };
    const item = barItem(options);
    const button = promotedOf(item, "checkout.tier");
    expect(countIn(button, '[data-dtb-part="flag-promoted-icon"]')).toBe(1);
    expect(button.getAttribute("aria-label")).toBe("First, gold");
    // "First wins" also means "Second loses": one entry, one control.
    expect(promotedIn(options)).toHaveLength(1);
    expect(countPromoted(item, "checkout.tier")).toBe(1);
  });

  it("publishes the chosen entry's position, and only for promoted flags", () => {
    const runtime = createFlagsRuntime({
      flags: CATALOGUE,
      promoted: [
        { flagKey: "checkout.tier", expiresAt: "2000-01-01T00:00:00.000Z" },
        { flagKey: "checkout.tier" },
      ],
    });
    const snapshot = runtime.store.peek();
    expect(snapshot.promoted).toHaveLength(1);
    const tier = snapshot.flags.find((view) => view.key === "checkout.tier") as FlagView;
    const header = snapshot.flags.find((view) => view.key === "new-header") as FlagView;
    expect(tier.promotedIndex).toBe(1);
    expect(header.promoted).toBe(false);
    expect(header.promotedIndex).toBeUndefined();
    // A number, so it can sit in the snapshot and in `signature()` — which is
    // the whole reason the index rather than the entry is what travels.
    expect(JSON.parse(JSON.stringify(tier))).toEqual(tier);
    runtime.store.destroy();
  });
});

describe("the render callback", () => {
  it("supplies the children and is told where it is painting", () => {
    const chipContexts: CompactRenderContext[] = [];
    const flagContexts: CompactRenderContext[] = [];
    const options: FlagsOptions = {
      presentation: {
        preset: "icon-value",
        icon: ICON,
        render: (snapshot: FlagsSnapshot, ctx: CompactRenderContext) => {
          chipContexts.push(ctx);
          return <b data-dtb-part="flag-custom">{snapshot.flags.length} flags</b>;
        },
      },
      ...promotedWith("checkout.tier", {
        render: (view: FlagView, ctx: CompactRenderContext) => {
          flagContexts.push(ctx);
          return <b data-dtb-part="flag-promoted-custom">{view.effectiveText}</b>;
        },
      }),
    };

    const item = barItem(options);
    expect(textIn(item, '[data-dtb-part="flag-custom"]')).toBe("2 flags");
    expect(textIn(item, '[data-dtb-part="flag-promoted-custom"]')).toBe("gold");
    // The consumer's node replaces the parts, not the control: the chip's
    // `data-dtb-overridden`, the promoted dot, the switch attributes and both
    // accessible names are not theirs to lose.
    expect(chipOf(item).getAttribute("data-dtb-overridden")).toBe("false");
    expect(triggerOf(item).getAttribute("aria-label")).toBe("Flags");
    const button = promotedOf(item, "checkout.tier");
    expect(button.querySelector('[data-dtb-part="flag-promoted-dot"]')).not.toBeNull();
    expect(button.getAttribute("aria-label")).toBe("checkout.tier, gold");
    expect(button.getAttribute("data-dtb-flag")).toBe("checkout.tier");
    expect(chipContexts[0]?.preset).toBe("icon-value");
    expect(chipContexts[0]?.icon).toBe(ICON);
    expect(chipContexts[0]?.isOverflowed).toBe(false);
    expect(chipContexts[0]?.isPanelOpen).toBe(false);
    expect(flagContexts[0]?.preset).toBe("default");

    // Honoured in the ⋮ menu too — ADR-004's deliberate deviation from the
    // "always paint text" guarantee, with `isOverflowed` as the hook. Both
    // controls keep their own `aria-label`, so a bare callback still leaves
    // named buttons.
    const menu = overflow(options);
    expect(textIn(menu, '[data-dtb-part="flag-custom"]')).toBe("2 flags");
    expect(chipContexts.at(-1)?.isOverflowed).toBe(true);
    expect(flagContexts.at(-1)?.isOverflowed).toBe(true);
  });

  it("falls through to the preset when it returns undefined", () => {
    const chipRender = vi.fn(() => undefined);
    const flagRender = vi.fn(() => undefined);
    const item = barItem({
      presentation: { preset: "icon-label", icon: ICON, render: chipRender },
      ...promotedWith("checkout.tier", { preset: "icon-label", icon: ICON, render: flagRender }),
    });
    expect(chipRender).toHaveBeenCalledTimes(1);
    expect(flagRender).toHaveBeenCalledTimes(1);
    expect(paintedChip(item)).toEqual({ icon: 1, text: "flags", value: null });
    expect(paintedFlag(item)).toEqual({ icon: 1, text: "checkout.tier", value: null });
  });

  it("returning ctx.fallback paints exactly what the preset would have", () => {
    // One construction, handed out as `fallback` and rendered as the preset —
    // so deferring is exact by construction rather than by careful mimicry.
    const presetOnly = barItem({
      presentation: { preset: "icon-value", icon: ICON },
      ...promotedWith("checkout.tier", { preset: "icon-value", icon: ICON }),
    }).innerHTML;
    const deferred = barItem({
      presentation: {
        preset: "icon-value",
        icon: ICON,
        render: (_snapshot: FlagsSnapshot, ctx: CompactRenderContext) => ctx.fallback,
      },
      ...promotedWith("checkout.tier", {
        preset: "icon-value",
        icon: ICON,
        render: (_view: FlagView, ctx: CompactRenderContext) => ctx.fallback,
      }),
    }).innerHTML;
    expect(deferred).toBe(presetOnly);
  });
});

describe("the accessible-name override", () => {
  it("replaces each control's aria-label, and leaves title alone", () => {
    const item = barItem({
      presentation: {
        preset: "icon",
        icon: ICON,
        name: (s: FlagsSnapshot) => `${s.flags.length} flags`,
      },
      ...promotedWith("checkout.tier", {
        preset: "icon",
        icon: ICON,
        name: (view: FlagView) => `Tier is ${view.effectiveText}`,
      }),
    });
    expect(triggerOf(item).getAttribute("aria-label")).toBe("2 flags");
    expect(promotedOf(item, "checkout.tier").getAttribute("aria-label")).toBe("Tier is gold");
    // `title` explains; it does not name, so it is not overridable.
    expect(triggerOf(item).getAttribute("title")).toBe(
      "Feature flags: 2 · 0 locally overridden · read-only",
    );
    expect(promotedOf(item, "checkout.tier").getAttribute("title")).toBe(
      "checkout.tier = gold · from default · click to open the flags panel",
    );
  });

  it("ignores a whitespace-only override rather than leaving a control unnamed", () => {
    // An icon-only control with no name is exactly what `/ext/a11y` would flag
    // on the toolbar's own bar.
    const item = barItem({
      presentation: { preset: "icon", icon: ICON, name: () => "   " },
      ...promotedWith("checkout.tier", { preset: "icon", icon: ICON, name: () => "" }),
    });
    expect(triggerOf(item).getAttribute("aria-label")).toBe("Flags");
    expect(promotedOf(item, "checkout.tier").getAttribute("aria-label")).toBe(
      "checkout.tier, gold",
    );
  });
});

describe("the hard rule: a ReactNode never enters the store", () => {
  /**
   * The reason `PromotedFlag.icon` was not widened to `ReactNode`. It is copied
   * into every snapshot as `FlagView.promotedIcon`, and this store publishes on
   * a string signature — so a node there would either never publish or
   * republish on every 250 ms tick, and would sit inside the object
   * `diagnostics()` serialises, one refactor away from a circular-structure
   * throw inside a click handler. `presentation` is config in the factory
   * closure instead, and these assertions are what says so.
   */
  const RICH: PromotedFlag = {
    flagKey: "checkout.tier",
    icon: "A",
    presentation: { preset: "icon", icon: ICON, render: () => ICON, name: () => "Tier" },
  };

  const richRuntime = () =>
    createFlagsRuntime({
      flags: CATALOGUE,
      promoted: [RICH],
      onOverride: () => {},
      now: () => 0,
    });

  /**
   * Asserts *structurally* rather than by looking for `"$$typeof"` in the JSON.
   *
   * `JSON.stringify` silently drops a Symbol-valued property, and a React
   * element's `$$typeof` is a Symbol — so `JSON.stringify({ icon: <svg/> })`
   * yields a `$$typeof`-free object and throws nothing. A marker search would
   * therefore pass with an element sitting in the snapshot: it could not fail
   * for the wrong reason, which makes it not evidence. A round-trip equality
   * check and an `isValidElement` walk can both fail, so they are.
   */
  const expectNoElements = (value: unknown): void => {
    expect(isValidElement(value)).toBe(false);
    if (value !== null && typeof value === "object") {
      Object.values(value).forEach(expectNoElements);
    }
  };

  it("keeps the snapshot serialisable with a JSX icon promoted", () => {
    const runtime = richRuntime();
    const snapshot = runtime.store.peek();
    // Round-trips unchanged: nothing in here is a value `JSON.stringify` drops
    // (a Symbol, a function, an `undefined`) or rewrites.
    expect(JSON.parse(JSON.stringify(snapshot))).toEqual(snapshot);
    expectNoElements(snapshot);
    expect(JSON.stringify(snapshot)).not.toContain("presentation");
    // The string glyph is still there, and still a string; the rich one never
    // arrived.
    const view = snapshot.promoted.find((entry) => entry.key === "checkout.tier") as FlagView;
    expect(typeof view.promotedIcon).toBe("string");
    expect(view.promotedIcon).toBe("A");
    runtime.store.destroy();
  });

  it("keeps diagnostics() serialisable with a JSX icon promoted", () => {
    const runtime = richRuntime();
    runtime.applyOverride("checkout.tier", "silver");
    const diagnostics = runtime.diagnostics();
    expect(JSON.parse(JSON.stringify(diagnostics))).toEqual(diagnostics);
    expectNoElements(diagnostics);
    // The marker search is the *wrong* tool one assertion up and the right one
    // here, and the difference is `redact()`.
    //
    // On a raw snapshot, `JSON.stringify` drops a Symbol-valued property
    // outright, so `$$typeof` would be missing from the JSON of an object that
    // really does hold an element: the search could not fail, which is why the
    // snapshot is checked structurally instead.
    //
    // `diagnostics()` ends in `redact()`, which deep-walks and *stringifies*
    // the Symbol to `"[symbol]"`. A leaked element therefore arrives here as a
    // plain object — `{"$$typeof":"[symbol]","type":"svg","_owner":…}` — and
    // the structural walk above goes blind, because `isValidElement` is false
    // on every node of it and the round-trip is equal. Post-`redact()` the
    // element's own field names are exactly what survives, so they are the only
    // thing left that can fail.
    expect(JSON.stringify(diagnostics)).not.toMatch(/\$\$typeof|"_owner"|"_store"/);
    expect(JSON.stringify(diagnostics)).toContain("checkout.tier");
    runtime.store.destroy();
  });

  it("keeps the copy-recipe path serialisable with a JSX icon promoted", () => {
    const runtime = richRuntime();
    runtime.applyOverride("checkout.tier", "silver");
    // `recipeText()` is typed `string`, so this path is clean by construction;
    // the assertion is that the promoted rich icon did not reach its content.
    const recipe = runtime.recipeText();
    expect(recipe).toBe("checkout.tier = silver (was gold)");
    runtime.store.destroy();
  });

  it("does not republish when only the presentation changes", () => {
    // The mirror image of the `BUG:`-marked test in `runtime.test.ts`: the
    // presentation is not signed because it is not in the snapshot at all,
    // which is the design rather than a gap. Changing it after the factory ran
    // is not supported — build the extension once, as the factory's JSDoc says.
    const promoted: PromotedFlag = { flagKey: "checkout.tier", presentation: "icon" };
    const runtime = createFlagsRuntime({ flags: CATALOGUE, promoted: [promoted], now: () => 0 });
    const before = runtime.store.getSnapshot();
    const listener = vi.fn();
    runtime.store.subscribe(listener);
    promoted.presentation = { preset: "icon-value", icon: ICON };
    runtime.refresh();
    runtime.store.flush();
    expect(listener).not.toHaveBeenCalled();
    expect(runtime.store.getSnapshot()).toBe(before);
    expectNoElements(runtime.store.peek());
    runtime.store.destroy();
  });
});
