/**
 * `/ext/environment`'s `presentation` option, against the real shell.
 *
 * Environment is the Group A deviant with **two button wrappers**: the bar
 * paints `data-dtb-part="trigger"` with `aria-expanded`, and the `⋮` row paints
 * `data-dtb-part="env-overflow"` with none — that row is not the disclosure the
 * bar trigger is. So everything here runs twice, and two things are pinned that
 * the other four Group A tests never have to state:
 *
 * 1. **Both wrappers are driven.** A preset, an icon, a `render` and a `name`
 *    reach the `⋮` row exactly as they reach the bar. The fork is about the
 *    element, not the presentation.
 * 2. **The `⋮` row still has no `aria-expanded`.** Under every preset, under a
 *    callback, and under a name override.
 *
 * Two further deviations from `/ext/a11y`'s dialect, both forced by
 * byte-identity rather than chosen:
 *
 * - the text span is **not** bare — it has always carried
 *   `data-dtb-part="env-label"` and `data-dtb-kind="label"`, and the kit
 *   sheet's `[data-dtb-kind="label"]` rule (`src/kit/css.ts`) tints the word;
 *   `/ext/environment`'s own sheet has no `env-label` rule at all; and
 * - `"default"` paints the short word `"env"` in the `⋮` row too, where the
 *   other Group A chips swing to their full label. A *preset* still forces the
 *   full label there, which is the kit's guarantee.
 *
 * The default output is pinned as literal strings in both places, in the state
 * that ships with no context and in an `impersonating` one — generated by
 * capture against the tree before this option existed, never by hand.
 * `resolveCompactParts` answering `null` for `"default"` is what makes
 * byte-identity structural; the strings are what make it evidence.
 *
 * [dev-toolbar/plans/bar-presentation-icons-v1 §4]
 */
import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanupToolbar, mountToolbar } from "@nejcm/dev-toolbar/testing";
import type { CompactPreset, CompactRenderContext } from "@nejcm/dev-toolbar/kit";
import { environment, kindLabel } from "../index";
import type { EnvironmentOptions } from "../index";
import type { EnvironmentSnapshot } from "../types";

/**
 * Tears down whatever is already mounted first: several tests here compare two
 * presentations of the same extension, and the testing helpers query the
 * document rather than one root, so a leftover toolbar answers for the new one.
 */
const mount = (options: EnvironmentOptions = {}) => {
  cleanupToolbar();
  return mountToolbar(null, {
    extensions: [environment(options)],
    layout: { barWidth: 900, itemWidth: 200 },
  });
};

const barTrigger = (options: EnvironmentOptions = {}): HTMLElement => {
  const { toolbar } = mount(options);
  const trigger = toolbar
    .item("environment")
    ?.querySelector<HTMLElement>('[data-dtb-part="trigger"]');
  expect(trigger).not.toBeNull();
  return trigger as HTMLElement;
};

/** The `⋮` row, with the bar collapsed to nothing. A *different element*. */
const overflowTrigger = (options: EnvironmentOptions = {}): HTMLElement => {
  const { toolbar } = mount(options);
  toolbar.resize(60);
  expect(toolbar.isOverflowed("environment")).toBe(true);
  toolbar.openOverflow();
  const trigger = toolbar
    .overflowMenu()
    ?.querySelector<HTMLElement>('[data-dtb-part="env-overflow"]');
  expect(trigger).not.toBeNull();
  return trigger as HTMLElement;
};

const barChip = (options: EnvironmentOptions = {}): HTMLElement =>
  barTrigger(options).querySelector('[data-dtb-part="env-chip"]') as HTMLElement;

const overflowChip = (options: EnvironmentOptions = {}): HTMLElement =>
  overflowTrigger(options).querySelector('[data-dtb-part="env-chip"]') as HTMLElement;

const text = (chip: Element): string | null =>
  chip.querySelector('[data-dtb-part="env-label"]')?.textContent ?? null;

const value = (chip: Element): string | null =>
  chip.querySelector('[data-dtb-part="env-value"]')?.textContent ?? null;

const icons = (element: Element): number =>
  element.querySelectorAll('[data-dtb-part="env-icon"]').length;

/** A consumer's own inline `<svg>` — the proof that nothing was bundled. */
const ICON = (
  <svg viewBox="0 0 16 16" data-icon="globe">
    <circle cx="8" cy="8" r="7" />
  </svg>
);

const IMPERSONATING: EnvironmentOptions = {
  context: { environment: "production", impersonating: true },
};

afterEach(cleanupToolbar);

describe("the default presentation", () => {
  // The exact markup that shipped before `presentation` existed, captured off
  // the previous tree. Regenerate it only against a deliberate, documented
  // change to environment's bar DOM: every consumer's CSS and every Playwright
  // selector reads these attributes.
  const DEFAULT_TRIGGER =
    '<button type="button" data-dtb-part="trigger" aria-expanded="false"' +
    ' aria-label="Environment, unknown"' +
    ' title="Environment: unknown — no context supplied to environment()">' +
    '<span data-dtb-part="env-chip" data-dtb-severity="unknown" data-dtb-kind="chip">' +
    '<span data-dtb-kind="dot" data-dtb-severity="unknown" aria-hidden="true"' +
    ' data-dtb-part="env-dot"></span>' +
    '<span data-dtb-part="env-label" data-dtb-kind="label">env</span>' +
    '<span data-dtb-kind="value" data-dtb-severity="unknown" data-dtb-part="env-value"' +
    ' data-dtb-env="unknown">unknown</span></span></button>';

  // The `⋮` row is a different *element* — no `aria-expanded` — and otherwise
  // the same tree, short word included. That is this extension's deviation
  // from the rest of Group A, and it is why `DEFAULTS.overflow.text` is
  // `"short"` here.
  const DEFAULT_OVERFLOW_TRIGGER = DEFAULT_TRIGGER.replace(
    ' data-dtb-part="trigger" aria-expanded="false"',
    ' data-dtb-part="env-overflow"',
  );

  // A state that is not the empty one: production, impersonating, so the
  // severity, the value word, the name and the `impersonating` child are all
  // something other than their defaults.
  const IMPERSONATING_TRIGGER =
    '<button type="button" data-dtb-part="trigger" aria-expanded="false"' +
    ' aria-label="Environment, production, impersonating"' +
    ' title="Environment: production — click for the full context">' +
    '<span data-dtb-part="env-chip" data-dtb-severity="bad" data-dtb-kind="chip">' +
    '<span data-dtb-kind="dot" data-dtb-severity="bad" aria-hidden="true"' +
    ' data-dtb-part="env-dot"></span>' +
    '<span data-dtb-part="env-label" data-dtb-kind="label">env</span>' +
    '<span data-dtb-kind="value" data-dtb-severity="bad" data-dtb-part="env-value"' +
    ' data-dtb-env="production">production</span>' +
    '<span data-dtb-part="env-alert">impersonating</span></span></button>';

  const IMPERSONATING_OVERFLOW_TRIGGER = IMPERSONATING_TRIGGER.replace(
    ' data-dtb-part="trigger" aria-expanded="false"',
    ' data-dtb-part="env-overflow"',
  );

  it("paints the bar byte-identically with no option at all", () => {
    expect(barTrigger().outerHTML).toBe(DEFAULT_TRIGGER);
  });

  it("paints the ⋮ row byte-identically with no option at all", () => {
    expect(overflowTrigger().outerHTML).toBe(DEFAULT_OVERFLOW_TRIGGER);
  });

  it("paints an impersonating production chip byte-identically, in both wrappers", () => {
    expect(barTrigger(IMPERSONATING).outerHTML).toBe(IMPERSONATING_TRIGGER);
    expect(overflowTrigger(IMPERSONATING).outerHTML).toBe(IMPERSONATING_OVERFLOW_TRIGGER);
  });

  it('is what an explicit "default" and a bare icon both resolve to', () => {
    // An icon with no preset that paints it does nothing — the four knobs are
    // meaningless apart, which is why they are one option.
    expect(barTrigger({ presentation: { preset: "default", icon: ICON } }).outerHTML).toBe(
      DEFAULT_TRIGGER,
    );
    expect(overflowTrigger({ presentation: "default" }).outerHTML).toBe(DEFAULT_OVERFLOW_TRIGGER);
  });
});

interface PresetRow {
  preset: CompactPreset;
  /** In the bar, with an icon supplied. */
  bar: { icon: boolean; text: string | null; value: string | null };
  /** In the `⋮` menu, with an icon supplied. */
  menu: { icon: boolean; text: string | null; value: string | null };
  /** In the bar, with no icon supplied. */
  bareBar: { text: string | null; value: string | null };
}

// Every member of the preset union, in both places. The completeness check
// below fails if a member goes missing.
const PRESETS: readonly PresetRow[] = [
  {
    // The only row where the menu keeps the short word: `"default"` means
    // what this extension shipped, and this extension shipped `"env"` in both.
    preset: "default",
    bar: { icon: false, text: "env", value: "unknown" },
    menu: { icon: false, text: "env", value: "unknown" },
    bareBar: { text: "env", value: "unknown" },
  },
  {
    preset: "icon",
    bar: { icon: true, text: null, value: null },
    // Guarantee 2 forces text in the menu — and the *full* label, which this
    // chip has never painted anywhere. Intended: a preset is the kit's
    // opinion, and the menu is never wordless under one.
    menu: { icon: true, text: "Environment", value: null },
    // Guarantee 1: an icon-only preset with no icon paints text, never nothing.
    bareBar: { text: "env", value: null },
  },
  {
    preset: "icon-value",
    bar: { icon: true, text: null, value: "unknown" },
    menu: { icon: true, text: "Environment", value: "unknown" },
    bareBar: { text: null, value: "unknown" },
  },
  {
    // The short bar word, the full label in the menu: the "which text" rule,
    // asserted rather than described.
    preset: "icon-label",
    bar: { icon: true, text: "env", value: null },
    menu: { icon: true, text: "Environment", value: null },
    bareBar: { text: "env", value: null },
  },
  {
    preset: "label",
    // "label" names no icon, so a supplied one is not painted.
    bar: { icon: false, text: "env", value: null },
    menu: { icon: false, text: "Environment", value: null },
    bareBar: { text: "env", value: null },
  },
  {
    preset: "value",
    bar: { icon: false, text: null, value: "unknown" },
    menu: { icon: false, text: "Environment", value: "unknown" },
    bareBar: { text: null, value: "unknown" },
  },
];

describe("presets", () => {
  it("covers every member of the preset union", () => {
    const members: Record<CompactPreset, true> = {
      default: true,
      icon: true,
      "icon-value": true,
      "icon-label": true,
      label: true,
      value: true,
    };
    expect(PRESETS.map((row) => row.preset).sort()).toEqual(Object.keys(members).sort());
  });

  it.each(PRESETS)("$preset in the bar, with an icon", ({ bar, preset }) => {
    const chip = barChip({ presentation: { preset, icon: ICON } });
    expect(icons(chip)).toBe(bar.icon ? 1 : 0);
    expect(text(chip)).toBe(bar.text);
    expect(value(chip)).toBe(bar.value);
  });

  it.each(PRESETS)("$preset in the ⋮ row, with an icon", ({ menu, preset }) => {
    // The second wrapper, driven by the same option — the deviation this file
    // exists for.
    const chip = overflowChip({ presentation: { preset, icon: ICON } });
    expect(icons(chip)).toBe(menu.icon ? 1 : 0);
    expect(text(chip)).toBe(menu.text);
    expect(value(chip)).toBe(menu.value);
  });

  it.each(PRESETS)("$preset in the bar, with no icon supplied", ({ bareBar, preset }) => {
    // The bare-preset shorthand, which is the 90% call: `presentation: "icon"`.
    const chip = barChip({ presentation: preset });
    expect(icons(chip)).toBe(0);
    expect(text(chip)).toBe(bareBar.text);
    expect(value(chip)).toBe(bareBar.value);
  });

  it.each(PRESETS)("$preset keeps the state, the dot and both wrappers' names", ({ preset }) => {
    const presentation = { preset, icon: ICON };
    const bar = barTrigger({ ...IMPERSONATING, presentation });
    const menu = overflowTrigger({ ...IMPERSONATING, presentation });

    for (const trigger of [bar, menu]) {
      const chip = trigger.querySelector('[data-dtb-part="env-chip"]') as HTMLElement;
      // A preset changes text, not state.
      expect(chip.getAttribute("data-dtb-severity")).toBe("bad");
      expect(
        chip.querySelector('[data-dtb-part="env-dot"]')?.getAttribute("data-dtb-severity"),
      ).toBe("bad");
      // Invariant 2: the `impersonating` child is state, outside the preset,
      // painted under every preset including `"icon"`.
      expect(chip.querySelector('[data-dtb-part="env-alert"]')?.textContent).toBe("impersonating");
      expect(trigger.getAttribute("aria-label")).toBe("Environment, production, impersonating");
      expect(trigger.getAttribute("title")).toBe(
        "Environment: production — click for the full context",
      );
    }

    // The fork itself: the bar discloses a panel, the `⋮` row does not.
    expect(bar.getAttribute("aria-expanded")).toBe("false");
    expect(menu.hasAttribute("aria-expanded")).toBe(false);
  });

  it("hides the icon from assistive technology and clamps it", () => {
    const glyph = barChip({ presentation: { preset: "icon", icon: ICON } }).querySelector(
      '[data-dtb-part="env-icon"]',
    );
    expect(glyph?.getAttribute("aria-hidden")).toBe("true");
    expect(glyph?.getAttribute("data-dtb-kind")).toBe("glyph");
    expect(glyph?.querySelector("svg")).not.toBeNull();
  });
});

describe("a function icon", () => {
  it("is invoked with the snapshot, so one option shape serves every extension", () => {
    const seen: EnvironmentSnapshot[] = [];
    const chip = barChip({
      ...IMPERSONATING,
      presentation: {
        preset: "icon",
        icon: (snapshot: EnvironmentSnapshot) => {
          seen.push(snapshot);
          // `kindLabel` is exported for exactly this: paint the value word the
          // preset would have painted, without re-deriving the rule.
          return <svg data-icon={kindLabel(snapshot)} />;
        },
      },
    });
    expect(seen[0]?.impersonating).toBe(true);
    expect(chip.querySelector('[data-dtb-part="env-icon"] svg')?.getAttribute("data-icon")).toBe(
      "production",
    );
  });

  it("paints text when it returns nothing", () => {
    // Guarantee 1 applies per control, after the function has been resolved.
    const chip = barChip({ presentation: { preset: "icon", icon: () => undefined } });
    expect(icons(chip)).toBe(0);
    expect(text(chip)).toBe("env");
  });
});

describe("the render callback", () => {
  it("supplies the chip's children in both wrappers, and is told where it is", () => {
    const contexts: CompactRenderContext[] = [];
    const render = (snapshot: EnvironmentSnapshot, ctx: CompactRenderContext) => {
      contexts.push(ctx);
      return <b data-dtb-part="env-custom">{kindLabel(snapshot)}!</b>;
    };
    const presentation = { preset: "icon-value" as const, icon: ICON, render };

    const bar = barTrigger({ ...IMPERSONATING, presentation });
    const barChipEl = bar.querySelector('[data-dtb-part="env-chip"]') as HTMLElement;
    expect(barChipEl.querySelector('[data-dtb-part="env-custom"]')?.textContent).toBe(
      "production!",
    );
    // The consumer's node replaces the parts, not the chip: the dot, the state
    // attribute, the `impersonating` marker and the name are not theirs to
    // lose. This is the whole reason the parts are `Chip`'s children rather
    // than its slots.
    expect(barChipEl.querySelector('[data-dtb-part="env-dot"]')).not.toBeNull();
    expect(barChipEl.querySelector('[data-dtb-part="env-alert"]')).not.toBeNull();
    expect(barChipEl.getAttribute("data-dtb-severity")).toBe("bad");
    expect(bar.getAttribute("aria-label")).toBe("Environment, production, impersonating");
    expect(value(barChipEl)).toBeNull();
    expect(contexts[0]?.preset).toBe("icon-value");
    expect(contexts[0]?.isOverflowed).toBe(false);
    expect(contexts[0]?.isPanelOpen).toBe(false);
    expect(contexts[0]?.icon).toBe(ICON);

    // Honoured in the ⋮ row too — ADR-004's deliberate deviation from the
    // "always paint text" guarantee, with `isOverflowed` as the hook. The row
    // keeps its own `aria-label` and still has no `aria-expanded`.
    const menu = overflowTrigger({ ...IMPERSONATING, presentation });
    expect(menu.querySelector('[data-dtb-part="env-custom"]')?.textContent).toBe("production!");
    expect(menu.querySelector('[data-dtb-part="env-alert"]')).not.toBeNull();
    expect(menu.getAttribute("aria-label")).toBe("Environment, production, impersonating");
    expect(menu.hasAttribute("aria-expanded")).toBe(false);
    expect(contexts.at(-1)?.isOverflowed).toBe(true);
  });

  it("falls through to the preset when it returns undefined", () => {
    const render = vi.fn(() => undefined);
    const chip = barChip({ presentation: { preset: "icon-label", icon: ICON, render } });
    expect(render).toHaveBeenCalledTimes(1);
    expect(icons(chip)).toBe(1);
    expect(text(chip)).toBe("env");
  });

  it("returning ctx.fallback paints exactly what the preset would have", () => {
    // One construction, handed out as `fallback` and rendered as the preset —
    // so deferring is exact by construction rather than by careful mimicry.
    const defer = (_snapshot: EnvironmentSnapshot, ctx: CompactRenderContext) => ctx.fallback;

    const presetOnly = barTrigger({ presentation: { preset: "icon-value", icon: ICON } });
    const deferred = barTrigger({
      presentation: { preset: "icon-value", icon: ICON, render: defer },
    });
    expect(deferred.outerHTML).toBe(presetOnly.outerHTML);

    const menuPresetOnly = overflowTrigger({ presentation: { preset: "icon", icon: ICON } });
    const menuDeferred = overflowTrigger({
      presentation: { preset: "icon", icon: ICON, render: defer },
    });
    expect(menuDeferred.outerHTML).toBe(menuPresetOnly.outerHTML);
  });
});

describe("the accessible-name override", () => {
  it("replaces the aria-label on both wrappers, and leaves title alone", () => {
    const presentation = {
      preset: "icon" as const,
      icon: ICON,
      name: (snapshot: EnvironmentSnapshot) => `Env: ${kindLabel(snapshot)}`,
    };
    for (const trigger of [
      barTrigger({ ...IMPERSONATING, presentation }),
      overflowTrigger({ ...IMPERSONATING, presentation }),
    ]) {
      expect(trigger.getAttribute("aria-label")).toBe("Env: production");
      // `title` explains; it does not name, so it is not overridable.
      expect(trigger.getAttribute("title")).toBe(
        "Environment: production — click for the full context",
      );
    }
  });

  it("ignores a whitespace-only override rather than leaving a wrapper unnamed", () => {
    const presentation = { preset: "icon" as const, icon: ICON, name: () => "   " };
    expect(barTrigger({ presentation }).getAttribute("aria-label")).toBe("Environment, unknown");
    expect(overflowTrigger({ presentation }).getAttribute("aria-label")).toBe(
      "Environment, unknown",
    );
  });
});
