/**
 * `/ext/theme-editor`'s `presentation` option, against the real shell.
 *
 * Theme-editor colours its own dot from `data-dtb-edited` / `data-dtb-preview`
 * instead of `severity` — the one thing every preset and `render` path must
 * leave unchanged (`plans/bar-presentation-icons-v1.md`, invariant 1). It also
 * paints the short word `"theme"` in the `⋮` row under `"default"`, unlike
 * a11y, diagnostics and overlays; a preset still forces the full label there.
 *
 * The default output is pinned as literal strings below, generated by capture
 * against the tree before this option existed — regenerate only that way,
 * never by hand.
 *
 * [dev-toolbar/plans/bar-presentation-icons-v1 §4]
 */
import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanupToolbar, mountToolbar } from "@nejcm/dev-toolbar/testing";
import type { ToolbarHandle } from "@nejcm/dev-toolbar/testing";
import type { CompactPreset, CompactRenderContext } from "@nejcm/dev-toolbar/kit";
import { themeEditor } from "../index";
import type { ThemeEditorOptions } from "../index";
import type { ThemeEditorBarView } from "../types";

const TOKENS = [{ name: "--brand", type: "color" as const, value: "#000000" }];

/**
 * Tears down any mounted toolbar first — tests compare two presentations, and
 * the testing helpers query the document, not one root.
 */
const mount = (options: ThemeEditorOptions = {}) => {
  cleanupToolbar();
  return mountToolbar(null, {
    extensions: [themeEditor({ tokens: TOKENS, ...options })],
    layout: { barWidth: 900, itemWidth: 200 },
  });
};

/**
 * Edits a token and pauses the preview — the non-default state pinned below.
 * Awaiting `runCommand` flushes the throttled store publish; a manual
 * `act()` also works but warns about overlapping acts.
 */
const edit = async (toolbar: ToolbarHandle): Promise<void> => {
  await toolbar.runCommand("theme-editor.setToken", { name: "--brand", value: "#ffffff" });
  await toolbar.runCommand("theme-editor.togglePreview");
};

const readBarTrigger = (toolbar: ToolbarHandle): HTMLElement => {
  const trigger = toolbar
    .item("theme-editor")
    ?.querySelector<HTMLElement>('[data-dtb-part="trigger"]');
  expect(trigger).not.toBeNull();
  return trigger as HTMLElement;
};

const barTrigger = (options: ThemeEditorOptions = {}): HTMLElement =>
  readBarTrigger(mount(options).toolbar);

/** The bar trigger, after an edit and a paused preview. */
const editedBarTrigger = async (options: ThemeEditorOptions = {}): Promise<HTMLElement> => {
  const { toolbar } = mount({ persist: false, ...options });
  await edit(toolbar);
  return readBarTrigger(toolbar);
};

const readOverflowTrigger = (toolbar: ToolbarHandle): HTMLElement => {
  toolbar.resize(60);
  expect(toolbar.isOverflowed("theme-editor")).toBe(true);
  toolbar.openOverflow();
  const trigger = toolbar
    .overflowMenu()
    ?.querySelector<HTMLElement>('[data-dtb-part="thm-overflow-trigger"]');
  expect(trigger).not.toBeNull();
  return trigger as HTMLElement;
};

/** The `⋮` row. The same element, renamed. */
const overflowTrigger = (options: ThemeEditorOptions = {}): HTMLElement =>
  readOverflowTrigger(mount(options).toolbar);

/** The `⋮` row, after an edit and a paused preview. */
const editedOverflowTrigger = async (options: ThemeEditorOptions = {}): Promise<HTMLElement> => {
  const { toolbar } = mount({ persist: false, ...options });
  await edit(toolbar);
  return readOverflowTrigger(toolbar);
};

const barChip = (options: ThemeEditorOptions = {}): HTMLElement =>
  barTrigger(options).querySelector('[data-dtb-part="thm-chip"]') as HTMLElement;

const overflowChip = (options: ThemeEditorOptions = {}): HTMLElement =>
  overflowTrigger(options).querySelector('[data-dtb-part="thm-chip"]') as HTMLElement;

/**
 * The chip's text span, selected by its `data-dtb-part`. Deliberately no
 * `data-dtb-kind="label"` — that's what the kit sheet tints with
 * `--dtb-muted`, and recolouring this chip is a separate decision.
 */
const text = (chip: Element): string | null =>
  chip.querySelector('[data-dtb-part="thm-label"]')?.textContent ?? null;

const value = (chip: Element): string | null =>
  chip.querySelector('[data-dtb-part="thm-count"]')?.textContent ?? null;

const icons = (element: Element): number =>
  element.querySelectorAll('[data-dtb-part="thm-icon"]').length;

/** A consumer's own inline `<svg>` — the proof that nothing was bundled. */
const ICON = (
  <svg viewBox="0 0 16 16" data-icon="palette">
    <circle cx="8" cy="8" r="7" />
  </svg>
);

afterEach(cleanupToolbar);

describe("the default presentation", () => {
  // Markup that shipped before `presentation` existed, captured off the
  // previous tree. Regenerate only by capture, against a deliberate DOM change.
  const DEFAULT_TRIGGER =
    '<button type="button" data-dtb-part="trigger" aria-expanded="false" aria-label="Theme"' +
    ' title="Design tokens: 1 · 0 edited locally">' +
    '<span data-dtb-part="thm-chip" data-dtb-edited="false" data-dtb-preview="true"' +
    ' data-dtb-kind="chip">' +
    '<span data-dtb-kind="dot" aria-hidden="true" data-dtb-part="thm-dot"></span>' +
    '<span data-dtb-part="thm-label">theme</span>' +
    '<span data-dtb-part="thm-count">1</span></span></button>';

  // The `⋮` row renames the part but keeps the short word — this
  // extension's deviation from the rest of Group A.
  const DEFAULT_OVERFLOW_TRIGGER = DEFAULT_TRIGGER.replace(
    'data-dtb-part="trigger"',
    'data-dtb-part="thm-overflow-trigger"',
  );

  // One token edited, preview paused — state attributes and the value word
  // both differ from above.
  const EDITED_TRIGGER =
    '<button type="button" data-dtb-part="trigger" aria-expanded="false"' +
    ' aria-label="Theme, 1 edited"' +
    ' title="Design tokens: 1 · 1 edited locally · preview paused — the app is showing its' +
    ' own values">' +
    '<span data-dtb-part="thm-chip" data-dtb-edited="true" data-dtb-preview="false"' +
    ' data-dtb-kind="chip">' +
    '<span data-dtb-kind="dot" aria-hidden="true" data-dtb-part="thm-dot"></span>' +
    '<span data-dtb-part="thm-label">theme</span>' +
    '<span data-dtb-part="thm-count">paused</span></span></button>';

  const EDITED_OVERFLOW_TRIGGER = EDITED_TRIGGER.replace(
    'data-dtb-part="trigger"',
    'data-dtb-part="thm-overflow-trigger"',
  );

  it("paints the bar byte-identically with no option at all", () => {
    expect(barTrigger().outerHTML).toBe(DEFAULT_TRIGGER);
  });

  it("paints the ⋮ row byte-identically with no option at all", () => {
    expect(overflowTrigger().outerHTML).toBe(DEFAULT_OVERFLOW_TRIGGER);
  });

  it("paints an edited, preview-paused chip byte-identically, in both places", async () => {
    // `persist: false` keeps the edit out of the next mount's storage.
    expect((await editedBarTrigger()).outerHTML).toBe(EDITED_TRIGGER);
    expect((await editedOverflowTrigger()).outerHTML).toBe(EDITED_OVERFLOW_TRIGGER);
  });

  it('is what an explicit "default" and a bare icon both resolve to', () => {
    // An icon with no preset to paint it does nothing — the four knobs are
    // one option because they're meaningless apart.
    expect(barTrigger({ presentation: { preset: "default", icon: ICON } }).outerHTML).toBe(
      DEFAULT_TRIGGER,
    );
    expect(overflowTrigger({ presentation: "default" }).outerHTML).toBe(DEFAULT_OVERFLOW_TRIGGER);
  });
});

interface PresetRow {
  preset: CompactPreset;
  /** In the bar, with an icon supplied. */
  bar: { icon: boolean; text: string | null; value: string | null };
  /** In the `⋮` menu, with an icon supplied. */
  menu: { icon: boolean; text: string | null; value: string | null };
  /** In the bar, with no icon supplied. */
  bareBar: { text: string | null; value: string | null };
}

// Every preset, in both places; the completeness check below catches a
// missing member.
const PRESETS: readonly PresetRow[] = [
  {
    // Only row where the menu keeps the short word — `"default"` is what
    // this extension already shipped, in both places.
    preset: "default",
    bar: { icon: false, text: "theme", value: "1" },
    menu: { icon: false, text: "theme", value: "1" },
    bareBar: { text: "theme", value: "1" },
  },
  {
    preset: "icon",
    bar: { icon: true, text: null, value: null },
    // Guarantee 2 forces the full label in the menu, which this chip never
    // otherwise paints — a preset is the kit's opinion, and the menu is
    // never wordless under one.
    menu: { icon: true, text: "Theme", value: null },
    // Guarantee 1: an icon-only preset with no icon paints text, never nothing.
    bareBar: { text: "theme", value: null },
  },
  {
    preset: "icon-value",
    bar: { icon: true, text: null, value: "1" },
    menu: { icon: true, text: "Theme", value: "1" },
    bareBar: { text: null, value: "1" },
  },
  {
    // Short word in the bar, full label in the menu — the "which text"
    // rule, asserted here.
    preset: "icon-label",
    bar: { icon: true, text: "theme", value: null },
    menu: { icon: true, text: "Theme", value: null },
    bareBar: { text: "theme", value: null },
  },
  {
    preset: "label",
    // "label" names no icon, so a supplied one is not painted.
    bar: { icon: false, text: "theme", value: null },
    menu: { icon: false, text: "Theme", value: null },
    bareBar: { text: "theme", value: null },
  },
  {
    preset: "value",
    bar: { icon: false, text: null, value: "1" },
    menu: { icon: false, text: "Theme", value: "1" },
    bareBar: { text: null, value: "1" },
  },
];

describe("presets", () => {
  it("covers every member of the preset union", () => {
    const members: Record<CompactPreset, true> = {
      default: true,
      icon: true,
      "icon-value": true,
      "icon-label": true,
      label: true,
      value: true,
    };
    expect(PRESETS.map((row) => row.preset).sort()).toEqual(Object.keys(members).sort());
  });

  it.each(PRESETS)("$preset in the bar, with an icon", ({ bar, preset }) => {
    const chip = barChip({ presentation: { preset, icon: ICON } });
    expect(icons(chip)).toBe(bar.icon ? 1 : 0);
    expect(text(chip)).toBe(bar.text);
    expect(value(chip)).toBe(bar.value);
  });

  it.each(PRESETS)("$preset in the ⋮ row, with an icon", ({ menu, preset }) => {
    const chip = overflowChip({ presentation: { preset, icon: ICON } });
    expect(icons(chip)).toBe(menu.icon ? 1 : 0);
    expect(text(chip)).toBe(menu.text);
    expect(value(chip)).toBe(menu.value);
  });

  it.each(PRESETS)("$preset in the bar, with no icon supplied", ({ bareBar, preset }) => {
    // The bare-preset shorthand, which is the 90% call: `presentation: "icon"`.
    const chip = barChip({ presentation: preset });
    expect(icons(chip)).toBe(0);
    expect(text(chip)).toBe(bareBar.text);
    expect(value(chip)).toBe(bareBar.value);
  });

  it.each(PRESETS)("$preset keeps the dot's own attributes and the name", async ({ preset }) => {
    const presentation = { preset, icon: ICON };
    for (const trigger of [
      await editedBarTrigger({ presentation }),
      await editedOverflowTrigger({ presentation }),
    ]) {
      const chip = trigger.querySelector('[data-dtb-part="thm-chip"]') as HTMLElement;
      // Invariant 1: the dot is coloured from these two attributes; a
      // preset changes text, not state.
      expect(chip.getAttribute("data-dtb-edited")).toBe("true");
      expect(chip.getAttribute("data-dtb-preview")).toBe("false");
      // No `severity` under any preset — this chip never writes one; adding
      // it would recolour from the kit's palette.
      expect(chip.hasAttribute("data-dtb-severity")).toBe(false);
      const dot = chip.querySelector('[data-dtb-part="thm-dot"]') as HTMLElement;
      expect(dot.getAttribute("data-dtb-kind")).toBe("dot");
      expect(dot.hasAttribute("data-dtb-severity")).toBe(false);
      expect(trigger.getAttribute("aria-label")).toBe("Theme, 1 edited");
      expect(trigger.getAttribute("aria-expanded")).toBe("false");
    }
  });

  it("keeps the value slot out of the kit's value kind under every preset", () => {
    for (const preset of ["default", "icon-value", "value"] as const) {
      const count = barChip({ presentation: { preset, icon: ICON } }).querySelector(
        '[data-dtb-part="thm-count"]',
      ) as HTMLElement;
      // Previously the `valueProps` opt-out; now just a hand-written span.
      // The count is unstyled.
      expect(count.hasAttribute("data-dtb-kind")).toBe(false);
      expect(count.hasAttribute("data-dtb-severity")).toBe(false);
    }
  });

  it("hides the icon from assistive technology and clamps it", () => {
    const glyph = barChip({ presentation: { preset: "icon", icon: ICON } }).querySelector(
      '[data-dtb-part="thm-icon"]',
    );
    expect(glyph?.getAttribute("aria-hidden")).toBe("true");
    expect(glyph?.getAttribute("data-dtb-kind")).toBe("glyph");
    expect(glyph?.querySelector("svg")).not.toBeNull();
  });
});

describe("a function icon", () => {
  it("is invoked with the narrow bar view, not the whole snapshot", () => {
    const seen: ThemeEditorBarView[] = [];
    const chip = barChip({
      presentation: {
        preset: "icon",
        icon: (view: ThemeEditorBarView) => {
          seen.push(view);
          return <svg data-icon={String(view.tokenCount)} />;
        },
      },
    });
    // Exactly the five facts the chip paints; token list, groups and apply
    // errors are deliberately excluded — a callback parameter is
    // contravariant and can't be extended later.
    expect(Object.keys(seen[0] ?? {}).sort()).toEqual([
      "overriddenCount",
      "preview",
      "supplied",
      "tokenCount",
      "writable",
    ]);
    expect(seen[0]?.tokenCount).toBe(1);
    expect(seen[0]?.overriddenCount).toBe(0);
    expect(seen[0]?.preview).toBe(true);
    expect(seen[0]?.supplied).toBe(true);
    expect(chip.querySelector('[data-dtb-part="thm-icon"] svg')?.getAttribute("data-icon")).toBe(
      "1",
    );
  });

  it("paints text when it returns nothing", () => {
    // Guarantee 1 applies per control, after the function has been resolved.
    const chip = barChip({ presentation: { preset: "icon", icon: () => undefined } });
    expect(icons(chip)).toBe(0);
    expect(text(chip)).toBe("theme");
  });
});

describe("the render callback", () => {
  it("supplies the chip's children and is told where it is painting", async () => {
    const contexts: CompactRenderContext[] = [];
    const render = (view: ThemeEditorBarView, ctx: CompactRenderContext) => {
      contexts.push(ctx);
      return <b data-dtb-part="thm-custom">{view.overriddenCount} edits</b>;
    };

    const trigger = await editedBarTrigger({
      presentation: { preset: "icon-value", icon: ICON, render },
    });
    const chip = trigger.querySelector('[data-dtb-part="thm-chip"]') as HTMLElement;
    expect(chip.querySelector('[data-dtb-part="thm-custom"]')?.textContent).toBe("1 edits");
    // The consumer's node replaces the chip's parts, not the chip itself —
    // the dot and its two colour attributes are not theirs to lose. Why the
    // parts are children, not slots.
    expect(chip.querySelector('[data-dtb-part="thm-dot"]')).not.toBeNull();
    expect(chip.getAttribute("data-dtb-edited")).toBe("true");
    expect(chip.getAttribute("data-dtb-preview")).toBe("false");
    expect(trigger.getAttribute("aria-label")).toBe("Theme, 1 edited");
    expect(value(chip)).toBeNull();
    expect(contexts[0]?.preset).toBe("icon-value");
    expect(contexts[0]?.isOverflowed).toBe(false);
    expect(contexts[0]?.isPanelOpen).toBe(false);
    expect(contexts[0]?.icon).toBe(ICON);

    // Honoured in the ⋮ row too (ADR-004's deviation from "always paint
    // text", via `isOverflowed`); the row keeps its own `aria-label`, so an
    // icon-only render still leaves a named button.
    const menu = overflowTrigger({ presentation: { render } });
    expect(menu.querySelector('[data-dtb-part="thm-custom"]')?.textContent).toBe("0 edits");
    expect(menu.querySelector('[data-dtb-part="thm-dot"]')).not.toBeNull();
    expect(menu.getAttribute("aria-label")).toBe("Theme");
    expect(contexts.at(-1)?.isOverflowed).toBe(true);
  });

  it("falls through to the preset when it returns undefined", () => {
    const render = vi.fn(() => undefined);
    const chip = barChip({ presentation: { preset: "icon-label", icon: ICON, render } });
    expect(render).toHaveBeenCalledTimes(1);
    expect(icons(chip)).toBe(1);
    expect(text(chip)).toBe("theme");
  });

  it("returning ctx.fallback paints exactly what the preset would have", () => {
    // `fallback` is the same construction used for the preset render, so
    // deferring is exact by construction.
    const defer = (_view: ThemeEditorBarView, ctx: CompactRenderContext) => ctx.fallback;

    const presetOnly = barTrigger({ presentation: { preset: "icon-value", icon: ICON } });
    const deferred = barTrigger({
      presentation: { preset: "icon-value", icon: ICON, render: defer },
    });
    expect(deferred.outerHTML).toBe(presetOnly.outerHTML);

    const menuPresetOnly = overflowTrigger({ presentation: { preset: "icon", icon: ICON } });
    const menuDeferred = overflowTrigger({
      presentation: { preset: "icon", icon: ICON, render: defer },
    });
    expect(menuDeferred.outerHTML).toBe(menuPresetOnly.outerHTML);
  });
});

describe("the accessible-name override", () => {
  it("replaces the trigger's aria-label, and leaves title alone", () => {
    const trigger = barTrigger({
      presentation: {
        preset: "icon",
        icon: ICON,
        name: (view: ThemeEditorBarView) => `Tokens: ${view.tokenCount}`,
      },
    });
    expect(trigger.getAttribute("aria-label")).toBe("Tokens: 1");
    // `title` explains; it does not name, so it is not overridable.
    expect(trigger.getAttribute("title")).toBe("Design tokens: 1 · 0 edited locally");
  });

  it("ignores a whitespace-only override rather than leaving the control unnamed", () => {
    const trigger = barTrigger({ presentation: { preset: "icon", icon: ICON, name: () => "   " } });
    expect(trigger.getAttribute("aria-label")).toBe("Theme");
  });
});
