/**
 * `/ext/theme-editor`'s `presentation` option, against the real shell.
 *
 * Theme-editor is the Group A deviant that **colours its own dot**. Every other
 * chip hands `Chip` a `severity` and takes the kit's dot and value colours;
 * this one passes none, opts its value slot out of the kit's `value` kind, and
 * paints from `data-dtb-edited` / `data-dtb-preview` instead. Those two
 * attributes are state, not text, so the thing this file exists to pin is that
 * they survive **every preset and every `render` path unchanged**
 * (`plans/bar-presentation-icons-v1.md`, invariant 1) — a consumer can restyle
 * the words next to the dot and can never change what colour the dot is.
 *
 * One further deviation from `/ext/a11y`'s dialect: `"default"` paints the
 * short word `"theme"` in the `⋮` row too, where a11y, diagnostics and overlays
 * swing to their full label. A *preset* still forces the full label there,
 * which is the kit's guarantee. The trigger is one element in both places — it
 * only renames its `data-dtb-part` — unlike `/ext/environment`'s two wrappers.
 *
 * The default output is pinned as literal strings in both places, in the state
 * that ships and in an edited, preview-paused one — generated by capture
 * against the tree before this option existed, never by hand.
 *
 * [dev-toolbar/plans/bar-presentation-icons-v1 §4]
 */
import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanupToolbar, mountToolbar } from "@nejcm/dev-toolbar/testing";
import type { ToolbarHandle } from "@nejcm/dev-toolbar/testing";
import type { CompactPreset, CompactRenderContext } from "@nejcm/dev-toolbar/kit";
import { themeEditor } from "../index";
import type { ThemeEditorOptions } from "../index";
import type { ThemeEditorBarView } from "../types";

const TOKENS = [{ name: "--brand", type: "color" as const, value: "#000000" }];

/**
 * Tears down whatever is already mounted first: several tests here compare two
 * presentations of the same extension, and the testing helpers query the
 * document rather than one root, so a leftover toolbar answers for the new one.
 */
const mount = (options: ThemeEditorOptions = {}) => {
  cleanupToolbar();
  return mountToolbar(null, {
    extensions: [themeEditor({ tokens: TOKENS, ...options })],
    layout: { barWidth: 900, itemWidth: 200 },
  });
};

/**
 * Edits a token and pauses the preview — the non-default state pinned below.
 *
 * Through `runCommand`, awaited: the helper `act()`s for us, and awaiting is
 * what flushes the throttled store publish. Wrapping the call in an `act()` of
 * our own works too, and warns about overlapping acts while it does it.
 */
const edit = async (toolbar: ToolbarHandle): Promise<void> => {
  await toolbar.runCommand("theme-editor.setToken", { name: "--brand", value: "#ffffff" });
  await toolbar.runCommand("theme-editor.togglePreview");
};

const readBarTrigger = (toolbar: ToolbarHandle): HTMLElement => {
  const trigger = toolbar
    .item("theme-editor")
    ?.querySelector<HTMLElement>('[data-dtb-part="trigger"]');
  expect(trigger).not.toBeNull();
  return trigger as HTMLElement;
};

const barTrigger = (options: ThemeEditorOptions = {}): HTMLElement =>
  readBarTrigger(mount(options).toolbar);

/** The bar trigger, after an edit and a paused preview. */
const editedBarTrigger = async (options: ThemeEditorOptions = {}): Promise<HTMLElement> => {
  const { toolbar } = mount({ persist: false, ...options });
  await edit(toolbar);
  return readBarTrigger(toolbar);
};

const readOverflowTrigger = (toolbar: ToolbarHandle): HTMLElement => {
  toolbar.resize(60);
  expect(toolbar.isOverflowed("theme-editor")).toBe(true);
  toolbar.openOverflow();
  const trigger = toolbar
    .overflowMenu()
    ?.querySelector<HTMLElement>('[data-dtb-part="thm-overflow-trigger"]');
  expect(trigger).not.toBeNull();
  return trigger as HTMLElement;
};

/** The `⋮` row. The same element, renamed. */
const overflowTrigger = (options: ThemeEditorOptions = {}): HTMLElement =>
  readOverflowTrigger(mount(options).toolbar);

/** The `⋮` row, after an edit and a paused preview. */
const editedOverflowTrigger = async (options: ThemeEditorOptions = {}): Promise<HTMLElement> => {
  const { toolbar } = mount({ persist: false, ...options });
  await edit(toolbar);
  return readOverflowTrigger(toolbar);
};

const barChip = (options: ThemeEditorOptions = {}): HTMLElement =>
  barTrigger(options).querySelector('[data-dtb-part="thm-chip"]') as HTMLElement;

const overflowChip = (options: ThemeEditorOptions = {}): HTMLElement =>
  overflowTrigger(options).querySelector('[data-dtb-part="thm-chip"]') as HTMLElement;

/**
 * The chip's text span, selected by the `data-dtb-part` it now carries.
 *
 * It used to be a bare `<span>` located structurally — the one child span with
 * no kind and no part of its own — because naming it would have changed the
 * bytes below. Naming it *is* the deliberate change this commit makes, so the
 * structural stand-in is gone and the selector says what it always meant.
 * There is deliberately no `data-dtb-kind="label"`: that is what the kit sheet
 * tints with `--dtb-muted`, and recolouring this chip is a separate decision.
 */
const text = (chip: Element): string | null =>
  chip.querySelector('[data-dtb-part="thm-label"]')?.textContent ?? null;

const value = (chip: Element): string | null =>
  chip.querySelector('[data-dtb-part="thm-count"]')?.textContent ?? null;

const icons = (element: Element): number =>
  element.querySelectorAll('[data-dtb-part="thm-icon"]').length;

/** A consumer's own inline `<svg>` — the proof that nothing was bundled. */
const ICON = (
  <svg viewBox="0 0 16 16" data-icon="palette">
    <circle cx="8" cy="8" r="7" />
  </svg>
);

afterEach(cleanupToolbar);

describe("the default presentation", () => {
  // The exact markup that shipped before `presentation` existed, captured off
  // the previous tree. Regenerate it only against a deliberate, documented
  // change to theme-editor's bar DOM: every consumer's CSS and every
  // Playwright selector reads these attributes.
  const DEFAULT_TRIGGER =
    '<button type="button" data-dtb-part="trigger" aria-expanded="false" aria-label="Theme"' +
    ' title="Design tokens: 1 · 0 edited locally">' +
    '<span data-dtb-part="thm-chip" data-dtb-edited="false" data-dtb-preview="true"' +
    ' data-dtb-kind="chip">' +
    '<span data-dtb-kind="dot" aria-hidden="true" data-dtb-part="thm-dot"></span>' +
    '<span data-dtb-part="thm-label">theme</span>' +
    '<span data-dtb-part="thm-count">1</span></span></button>';

  // The `⋮` row renames the part and keeps everything else, short word
  // included. That is this extension's deviation from the rest of Group A,
  // and it is why `DEFAULTS.overflow.text` is `"short"` here.
  const DEFAULT_OVERFLOW_TRIGGER = DEFAULT_TRIGGER.replace(
    'data-dtb-part="trigger"',
    'data-dtb-part="thm-overflow-trigger"',
  );

  // A state that is neither empty nor clean: one token edited, and the preview
  // paused, so both state attributes and the value word differ from above.
  const EDITED_TRIGGER =
    '<button type="button" data-dtb-part="trigger" aria-expanded="false"' +
    ' aria-label="Theme, 1 edited"' +
    ' title="Design tokens: 1 · 1 edited locally · preview paused — the app is showing its' +
    ' own values">' +
    '<span data-dtb-part="thm-chip" data-dtb-edited="true" data-dtb-preview="false"' +
    ' data-dtb-kind="chip">' +
    '<span data-dtb-kind="dot" aria-hidden="true" data-dtb-part="thm-dot"></span>' +
    '<span data-dtb-part="thm-label">theme</span>' +
    '<span data-dtb-part="thm-count">paused</span></span></button>';

  const EDITED_OVERFLOW_TRIGGER = EDITED_TRIGGER.replace(
    'data-dtb-part="trigger"',
    'data-dtb-part="thm-overflow-trigger"',
  );

  it("paints the bar byte-identically with no option at all", () => {
    expect(barTrigger().outerHTML).toBe(DEFAULT_TRIGGER);
  });

  it("paints the ⋮ row byte-identically with no option at all", () => {
    expect(overflowTrigger().outerHTML).toBe(DEFAULT_OVERFLOW_TRIGGER);
  });

  it("paints an edited, preview-paused chip byte-identically, in both places", async () => {
    // `persist: false` so the edit stays in this test rather than in the next
    // mount's storage.
    expect((await editedBarTrigger()).outerHTML).toBe(EDITED_TRIGGER);
    expect((await editedOverflowTrigger()).outerHTML).toBe(EDITED_OVERFLOW_TRIGGER);
  });

  it('is what an explicit "default" and a bare icon both resolve to', () => {
    // An icon with no preset that paints it does nothing — the four knobs are
    // meaningless apart, which is why they are one option.
    expect(barTrigger({ presentation: { preset: "default", icon: ICON } }).outerHTML).toBe(
      DEFAULT_TRIGGER,
    );
    expect(overflowTrigger({ presentation: "default" }).outerHTML).toBe(DEFAULT_OVERFLOW_TRIGGER);
  });
});

interface PresetRow {
  preset: CompactPreset;
  /** In the bar, with an icon supplied. */
  bar: { icon: boolean; text: string | null; value: string | null };
  /** In the `⋮` menu, with an icon supplied. */
  menu: { icon: boolean; text: string | null; value: string | null };
  /** In the bar, with no icon supplied. */
  bareBar: { text: string | null; value: string | null };
}

// Every member of the preset union, in both places. The completeness check
// below fails if a member goes missing.
const PRESETS: readonly PresetRow[] = [
  {
    // The only row where the menu keeps the short word: `"default"` means
    // what this extension shipped, and this extension shipped `"theme"` in
    // both places.
    preset: "default",
    bar: { icon: false, text: "theme", value: "1" },
    menu: { icon: false, text: "theme", value: "1" },
    bareBar: { text: "theme", value: "1" },
  },
  {
    preset: "icon",
    bar: { icon: true, text: null, value: null },
    // Guarantee 2 forces text in the menu — and the *full* label, which this
    // chip has never painted anywhere. Intended: a preset is the kit's
    // opinion, and the menu is never wordless under one.
    menu: { icon: true, text: "Theme", value: null },
    // Guarantee 1: an icon-only preset with no icon paints text, never nothing.
    bareBar: { text: "theme", value: null },
  },
  {
    preset: "icon-value",
    bar: { icon: true, text: null, value: "1" },
    menu: { icon: true, text: "Theme", value: "1" },
    bareBar: { text: null, value: "1" },
  },
  {
    // The short bar word, the full label in the menu: the "which text" rule,
    // asserted rather than described.
    preset: "icon-label",
    bar: { icon: true, text: "theme", value: null },
    menu: { icon: true, text: "Theme", value: null },
    bareBar: { text: "theme", value: null },
  },
  {
    preset: "label",
    // "label" names no icon, so a supplied one is not painted.
    bar: { icon: false, text: "theme", value: null },
    menu: { icon: false, text: "Theme", value: null },
    bareBar: { text: "theme", value: null },
  },
  {
    preset: "value",
    bar: { icon: false, text: null, value: "1" },
    menu: { icon: false, text: "Theme", value: "1" },
    bareBar: { text: null, value: "1" },
  },
];

describe("presets", () => {
  it("covers every member of the preset union", () => {
    const members: Record<CompactPreset, true> = {
      default: true,
      icon: true,
      "icon-value": true,
      "icon-label": true,
      label: true,
      value: true,
    };
    expect(PRESETS.map((row) => row.preset).sort()).toEqual(Object.keys(members).sort());
  });

  it.each(PRESETS)("$preset in the bar, with an icon", ({ bar, preset }) => {
    const chip = barChip({ presentation: { preset, icon: ICON } });
    expect(icons(chip)).toBe(bar.icon ? 1 : 0);
    expect(text(chip)).toBe(bar.text);
    expect(value(chip)).toBe(bar.value);
  });

  it.each(PRESETS)("$preset in the ⋮ row, with an icon", ({ menu, preset }) => {
    const chip = overflowChip({ presentation: { preset, icon: ICON } });
    expect(icons(chip)).toBe(menu.icon ? 1 : 0);
    expect(text(chip)).toBe(menu.text);
    expect(value(chip)).toBe(menu.value);
  });

  it.each(PRESETS)("$preset in the bar, with no icon supplied", ({ bareBar, preset }) => {
    // The bare-preset shorthand, which is the 90% call: `presentation: "icon"`.
    const chip = barChip({ presentation: preset });
    expect(icons(chip)).toBe(0);
    expect(text(chip)).toBe(bareBar.text);
    expect(value(chip)).toBe(bareBar.value);
  });

  it.each(PRESETS)("$preset keeps the dot's own attributes and the name", async ({ preset }) => {
    const presentation = { preset, icon: ICON };
    for (const trigger of [
      await editedBarTrigger({ presentation }),
      await editedOverflowTrigger({ presentation }),
    ]) {
      const chip = trigger.querySelector('[data-dtb-part="thm-chip"]') as HTMLElement;
      // Invariant 1, and the reason this extension is a deviant: the dot is
      // coloured from these two, and a preset changes text, not state.
      expect(chip.getAttribute("data-dtb-edited")).toBe("true");
      expect(chip.getAttribute("data-dtb-preview")).toBe("false");
      // No severity anywhere, under any preset — this chip has never written
      // one, and adding one would recolour it from the kit's palette.
      expect(chip.hasAttribute("data-dtb-severity")).toBe(false);
      const dot = chip.querySelector('[data-dtb-part="thm-dot"]') as HTMLElement;
      expect(dot.getAttribute("data-dtb-kind")).toBe("dot");
      expect(dot.hasAttribute("data-dtb-severity")).toBe(false);
      expect(trigger.getAttribute("aria-label")).toBe("Theme, 1 edited");
      expect(trigger.getAttribute("aria-expanded")).toBe("false");
    }
  });

  it("keeps the value slot out of the kit's value kind under every preset", () => {
    for (const preset of ["default", "icon-value", "value"] as const) {
      const count = barChip({ presentation: { preset, icon: ICON } }).querySelector(
        '[data-dtb-part="thm-count"]',
      ) as HTMLElement;
      // The opt-out `valueProps={{ "data-dtb-kind": undefined }}` used to do,
      // now expressed by writing the span by hand. The count is unstyled here.
      expect(count.hasAttribute("data-dtb-kind")).toBe(false);
      expect(count.hasAttribute("data-dtb-severity")).toBe(false);
    }
  });

  it("hides the icon from assistive technology and clamps it", () => {
    const glyph = barChip({ presentation: { preset: "icon", icon: ICON } }).querySelector(
      '[data-dtb-part="thm-icon"]',
    );
    expect(glyph?.getAttribute("aria-hidden")).toBe("true");
    expect(glyph?.getAttribute("data-dtb-kind")).toBe("glyph");
    expect(glyph?.querySelector("svg")).not.toBeNull();
  });
});

describe("a function icon", () => {
  it("is invoked with the narrow bar view, not the whole snapshot", () => {
    const seen: ThemeEditorBarView[] = [];
    const chip = barChip({
      presentation: {
        preset: "icon",
        icon: (view: ThemeEditorBarView) => {
          seen.push(view);
          return <svg data-icon={String(view.tokenCount)} />;
        },
      },
    });
    // Exactly the five facts the chip paints — the editor's token list, groups
    // and apply errors are not a callback parameter, because a callback
    // parameter is contravariant and cannot then be renamed.
    expect(Object.keys(seen[0] ?? {}).sort()).toEqual([
      "overriddenCount",
      "preview",
      "supplied",
      "tokenCount",
      "writable",
    ]);
    expect(seen[0]?.tokenCount).toBe(1);
    expect(seen[0]?.overriddenCount).toBe(0);
    expect(seen[0]?.preview).toBe(true);
    expect(seen[0]?.supplied).toBe(true);
    expect(chip.querySelector('[data-dtb-part="thm-icon"] svg')?.getAttribute("data-icon")).toBe(
      "1",
    );
  });

  it("paints text when it returns nothing", () => {
    // Guarantee 1 applies per control, after the function has been resolved.
    const chip = barChip({ presentation: { preset: "icon", icon: () => undefined } });
    expect(icons(chip)).toBe(0);
    expect(text(chip)).toBe("theme");
  });
});

describe("the render callback", () => {
  it("supplies the chip's children and is told where it is painting", async () => {
    const contexts: CompactRenderContext[] = [];
    const render = (view: ThemeEditorBarView, ctx: CompactRenderContext) => {
      contexts.push(ctx);
      return <b data-dtb-part="thm-custom">{view.overriddenCount} edits</b>;
    };

    const trigger = await editedBarTrigger({
      presentation: { preset: "icon-value", icon: ICON, render },
    });
    const chip = trigger.querySelector('[data-dtb-part="thm-chip"]') as HTMLElement;
    expect(chip.querySelector('[data-dtb-part="thm-custom"]')?.textContent).toBe("1 edits");
    // The consumer's node replaces the parts, not the chip: the dot and the
    // two attributes it takes its colour from are not theirs to lose. This is
    // the whole reason the parts are `Chip`'s children rather than its slots.
    expect(chip.querySelector('[data-dtb-part="thm-dot"]')).not.toBeNull();
    expect(chip.getAttribute("data-dtb-edited")).toBe("true");
    expect(chip.getAttribute("data-dtb-preview")).toBe("false");
    expect(trigger.getAttribute("aria-label")).toBe("Theme, 1 edited");
    expect(value(chip)).toBeNull();
    expect(contexts[0]?.preset).toBe("icon-value");
    expect(contexts[0]?.isOverflowed).toBe(false);
    expect(contexts[0]?.isPanelOpen).toBe(false);
    expect(contexts[0]?.icon).toBe(ICON);

    // Honoured in the ⋮ row too — ADR-004's deliberate deviation from the
    // "always paint text" guarantee, with `isOverflowed` as the hook. The row
    // keeps its own `aria-label`, so a callback painting an icon alone still
    // leaves a named button.
    const menu = overflowTrigger({ presentation: { render } });
    expect(menu.querySelector('[data-dtb-part="thm-custom"]')?.textContent).toBe("0 edits");
    expect(menu.querySelector('[data-dtb-part="thm-dot"]')).not.toBeNull();
    expect(menu.getAttribute("aria-label")).toBe("Theme");
    expect(contexts.at(-1)?.isOverflowed).toBe(true);
  });

  it("falls through to the preset when it returns undefined", () => {
    const render = vi.fn(() => undefined);
    const chip = barChip({ presentation: { preset: "icon-label", icon: ICON, render } });
    expect(render).toHaveBeenCalledTimes(1);
    expect(icons(chip)).toBe(1);
    expect(text(chip)).toBe("theme");
  });

  it("returning ctx.fallback paints exactly what the preset would have", () => {
    // One construction, handed out as `fallback` and rendered as the preset —
    // so deferring is exact by construction rather than by careful mimicry.
    const defer = (_view: ThemeEditorBarView, ctx: CompactRenderContext) => ctx.fallback;

    const presetOnly = barTrigger({ presentation: { preset: "icon-value", icon: ICON } });
    const deferred = barTrigger({
      presentation: { preset: "icon-value", icon: ICON, render: defer },
    });
    expect(deferred.outerHTML).toBe(presetOnly.outerHTML);

    const menuPresetOnly = overflowTrigger({ presentation: { preset: "icon", icon: ICON } });
    const menuDeferred = overflowTrigger({
      presentation: { preset: "icon", icon: ICON, render: defer },
    });
    expect(menuDeferred.outerHTML).toBe(menuPresetOnly.outerHTML);
  });
});

describe("the accessible-name override", () => {
  it("replaces the trigger's aria-label, and leaves title alone", () => {
    const trigger = barTrigger({
      presentation: {
        preset: "icon",
        icon: ICON,
        name: (view: ThemeEditorBarView) => `Tokens: ${view.tokenCount}`,
      },
    });
    expect(trigger.getAttribute("aria-label")).toBe("Tokens: 1");
    // `title` explains; it does not name, so it is not overridable.
    expect(trigger.getAttribute("title")).toBe("Design tokens: 1 · 0 edited locally");
  });

  it("ignores a whitespace-only override rather than leaving the control unnamed", () => {
    const trigger = barTrigger({ presentation: { preset: "icon", icon: ICON, name: () => "   " } });
    expect(trigger.getAttribute("aria-label")).toBe("Theme");
  });
});
